insert into tblDecimalCategory values (0, '000', '총류');
insert into tblDecimalCategory values (1, '001', '지식 및 학문 일반');
insert into tblDecimalCategory values (2, '002', '미사용');
insert into tblDecimalCategory values (3, '003', '이론 체계 및 시스템');
insert into tblDecimalCategory values (4, '004', '컴퓨터과학');
insert into tblDecimalCategory values (5, '005', '프로그래밍, 프로그램, 데이터');
insert into tblDecimalCategory values (6, '006', '미사용');
insert into tblDecimalCategory values (7, '007', '미사용');
insert into tblDecimalCategory values (8, '008', '미사용');
insert into tblDecimalCategory values (9, '009', '미사용');
insert into tblDecimalCategory values (10, '010', '도서학, 서지학');
insert into tblDecimalCategory values (11, '011', '저작');
insert into tblDecimalCategory values (12, '012', '필사본, 판본, 제본');
insert into tblDecimalCategory values (13, '013', '출판 및 판매');
insert into tblDecimalCategory values (14, '014', '개인서지 및 목록');
insert into tblDecimalCategory values (15, '015', '국가별 서지 및 목록');
insert into tblDecimalCategory values (16, '016', '주제별 서지 및 목록');
insert into tblDecimalCategory values (17, '017', '특수서지 및 목록');
insert into tblDecimalCategory values (18, '018', '일반서지 및 목록');
insert into tblDecimalCategory values (19, '019', '장서목록');
insert into tblDecimalCategory values (20, '020', '문헌정보학');
insert into tblDecimalCategory values (21, '021', '도서관 행정 및 제정');
insert into tblDecimalCategory values (22, '022', '도서관 건축 및 설비');
insert into tblDecimalCategory values (23, '023', '도서관 경영, 관리');
insert into tblDecimalCategory values (24, '024', '수서, 정리 및 보존');
insert into tblDecimalCategory values (25, '025', '도서관 봉사 및 활동');
insert into tblDecimalCategory values (26, '026', '일반 도서관');
insert into tblDecimalCategory values (27, '027', '학교 및 대학 도서관');
insert into tblDecimalCategory values (28, '028', '기록관리학');
insert into tblDecimalCategory values (29, '029', '독서 및 정보매체의 이용');
insert into tblDecimalCategory values (30, '030', '백과사전');
insert into tblDecimalCategory values (31, '031', '한국어');
insert into tblDecimalCategory values (32, '032', '중국어');
insert into tblDecimalCategory values (33, '033', '일본어');
insert into tblDecimalCategory values (34, '034', '영어');
insert into tblDecimalCategory values (35, '035', '독일어');
insert into tblDecimalCategory values (36, '036', '프랑스어');
insert into tblDecimalCategory values (37, '037', '스페인어');
insert into tblDecimalCategory values (38, '038', '이탈리아어');
insert into tblDecimalCategory values (39, '039', '기타 제언어');
insert into tblDecimalCategory values (40, '040', '강연집, 수필집, 연설문집');
insert into tblDecimalCategory values (41, '041', '한국어');
insert into tblDecimalCategory values (42, '042', '중국어');
insert into tblDecimalCategory values (43, '043', '일본어');
insert into tblDecimalCategory values (44, '044', '영어');
insert into tblDecimalCategory values (45, '045', '독일어');
insert into tblDecimalCategory values (46, '046', '프랑스어');
insert into tblDecimalCategory values (47, '047', '스페인어');
insert into tblDecimalCategory values (48, '048', '이탈리아어');
insert into tblDecimalCategory values (49, '049', '기타 제언어');
insert into tblDecimalCategory values (50, '050', '일반연속간행물');
insert into tblDecimalCategory values (51, '051', '한국어');
insert into tblDecimalCategory values (52, '052', '중국어');
insert into tblDecimalCategory values (53, '053', '일본어');
insert into tblDecimalCategory values (54, '054', '영어');
insert into tblDecimalCategory values (55, '055', '독일어');
insert into tblDecimalCategory values (56, '056', '프랑스어');
insert into tblDecimalCategory values (57, '057', '스페인어');
insert into tblDecimalCategory values (58, '058', '기타 제언어');
insert into tblDecimalCategory values (59, '059', '연감');
insert into tblDecimalCategory values (60, '060', '일반 학회, 단체, 협회, 기관, 연구기관');
insert into tblDecimalCategory values (61, '061', '아시아');
insert into tblDecimalCategory values (62, '062', '유럽');
insert into tblDecimalCategory values (63, '063', '아프리카');
insert into tblDecimalCategory values (64, '064', '북아메리카');
insert into tblDecimalCategory values (65, '065', '남아메리카');
insert into tblDecimalCategory values (66, '066', '오세아니아, 양극지방');
insert into tblDecimalCategory values (67, '067', '일반지역');
insert into tblDecimalCategory values (68, '068', '해양');
insert into tblDecimalCategory values (69, '069', '박물관학');
insert into tblDecimalCategory values (70, '070', '신문, 저널리즘');
insert into tblDecimalCategory values (71, '071', '아시아');
insert into tblDecimalCategory values (72, '072', '유럽');
insert into tblDecimalCategory values (73, '073', '아프리카');
insert into tblDecimalCategory values (74, '074', '북아메리카');
insert into tblDecimalCategory values (75, '075', '남아메리카');
insert into tblDecimalCategory values (76, '076', '오세아니아, 양극지방');
insert into tblDecimalCategory values (77, '077', '일반지역');
insert into tblDecimalCategory values (78, '078', '특정주제의 신문');
insert into tblDecimalCategory values (79, '079', '미사용');
insert into tblDecimalCategory values (80, '080', '일반 전집, 총서');
insert into tblDecimalCategory values (81, '081', '개인의 일반전집');
insert into tblDecimalCategory values (82, '082', '2인 이상의 일반전집, 총서');
insert into tblDecimalCategory values (83, '083', '미사용');
insert into tblDecimalCategory values (84, '084', '미사용');
insert into tblDecimalCategory values (85, '085', '미사용');
insert into tblDecimalCategory values (86, '086', '미사용');
insert into tblDecimalCategory values (87, '087', '미사용');
insert into tblDecimalCategory values (88, '088', '미사용');
insert into tblDecimalCategory values (89, '089', '미사용');
insert into tblDecimalCategory values (90, '090', '향토자료');
insert into tblDecimalCategory values (91, '091', '미사용');
insert into tblDecimalCategory values (92, '092', '미사용');
insert into tblDecimalCategory values (93, '093', '미사용');
insert into tblDecimalCategory values (94, '094', '미사용');
insert into tblDecimalCategory values (95, '095', '미사용');
insert into tblDecimalCategory values (96, '096', '미사용');
insert into tblDecimalCategory values (97, '097', '미사용');
insert into tblDecimalCategory values (98, '098', '미사용');
insert into tblDecimalCategory values (99, '099', '미사용');
insert into tblDecimalCategory values (100, '100', '철학');
insert into tblDecimalCategory values (101, '101', '철학 및 이론의 효용');
insert into tblDecimalCategory values (102, '102', '잡저');
insert into tblDecimalCategory values (103, '103', '사전, 사전[2], 용어사전');
insert into tblDecimalCategory values (104, '104', '강연집, 수필집');
insert into tblDecimalCategory values (105, '105', '연속간행물');
insert into tblDecimalCategory values (106, '106', '학회, 단체, 협회, 기관, 회의');
insert into tblDecimalCategory values (107, '107', '지도법, 연구법 및 교육, 교육자료');
insert into tblDecimalCategory values (108, '108', '총서, 전집, 선집');
insert into tblDecimalCategory values (109, '109', '철학사');
insert into tblDecimalCategory values (110, '110', '형이상학');
insert into tblDecimalCategory values (111, '111', '방법론');
insert into tblDecimalCategory values (112, '112', '존재론');
insert into tblDecimalCategory values (113, '113', '우주론 및 자연철학');
insert into tblDecimalCategory values (114, '114', '공간');
insert into tblDecimalCategory values (115, '115', '시간');
insert into tblDecimalCategory values (116, '116', '운동과 변화');
insert into tblDecimalCategory values (117, '117', '구조');
insert into tblDecimalCategory values (118, '118', '힘과 에너지');
insert into tblDecimalCategory values (119, '119', '물량과 질량');
insert into tblDecimalCategory values (120, '120', '인식론, 인과론, 인간학');
insert into tblDecimalCategory values (121, '121', '인식론');
insert into tblDecimalCategory values (122, '122', '인과론');
insert into tblDecimalCategory values (123, '123', '자유 및 필연');
insert into tblDecimalCategory values (124, '124', '목적론');
insert into tblDecimalCategory values (125, '125', '가치론');
insert into tblDecimalCategory values (126, '126', '철학적 인간학');
insert into tblDecimalCategory values (127, '127', '미사용');
insert into tblDecimalCategory values (128, '128', '미사용');
insert into tblDecimalCategory values (129, '129', '미사용');
insert into tblDecimalCategory values (130, '130', '철학의 체계');
insert into tblDecimalCategory values (131, '131', '관념론 및 연관철학');
insert into tblDecimalCategory values (132, '132', '비판철학');
insert into tblDecimalCategory values (133, '133', '합리론');
insert into tblDecimalCategory values (134, '134', '인문주의');
insert into tblDecimalCategory values (135, '135', '경험론');
insert into tblDecimalCategory values (136, '136', '자연주의');
insert into tblDecimalCategory values (137, '137', '유물론');
insert into tblDecimalCategory values (138, '138', '과학주의');
insert into tblDecimalCategory values (139, '139', '기타');
insert into tblDecimalCategory values (140, '140', '경학');
insert into tblDecimalCategory values (141, '141', '역류(한역)');
insert into tblDecimalCategory values (142, '142', '서류');
insert into tblDecimalCategory values (143, '143', '시류');
insert into tblDecimalCategory values (144, '144', '예류');
insert into tblDecimalCategory values (145, '145', '악류');
insert into tblDecimalCategory values (146, '146', '춘추류');
insert into tblDecimalCategory values (147, '147', '효경');
insert into tblDecimalCategory values (148, '148', '사서');
insert into tblDecimalCategory values (149, '149', '미사용');
insert into tblDecimalCategory values (150, '150', '동양철학, 동양사상');
insert into tblDecimalCategory values (151, '151', '한국 철학, 사상');
insert into tblDecimalCategory values (152, '152', '중국 철학, 사상');
insert into tblDecimalCategory values (153, '153', '일본 철학 사상');
insert into tblDecimalCategory values (154, '154', '동남아시아 제국 철학, 사상');
insert into tblDecimalCategory values (155, '155', '인도 철학, 사상');
insert into tblDecimalCategory values (156, '156', '중앙아시아 제국 철학, 사상');
insert into tblDecimalCategory values (157, '157', '시베리아 철학, 사상');
insert into tblDecimalCategory values (158, '158', '서남아시아 제국 철학, 사상');
insert into tblDecimalCategory values (159, '159', '아라비아반도 철학, 사상');
insert into tblDecimalCategory values (160, '160', '서양철학');
insert into tblDecimalCategory values (161, '161', '미사용');
insert into tblDecimalCategory values (162, '162', '미국철학');
insert into tblDecimalCategory values (163, '163', '북구철학');
insert into tblDecimalCategory values (164, '164', '영국철학');
insert into tblDecimalCategory values (165, '165', '독일, 오스트리아 철학');
insert into tblDecimalCategory values (166, '166', '프랑스, 네덜란드 철학');
insert into tblDecimalCategory values (167, '167', '스페인철학');
insert into tblDecimalCategory values (168, '168', '이탈리아철학');
insert into tblDecimalCategory values (169, '169', '러시아철학');
insert into tblDecimalCategory values (170, '170', '논리학');
insert into tblDecimalCategory values (171, '171', '연역법');
insert into tblDecimalCategory values (172, '172', '귀납법');
insert into tblDecimalCategory values (173, '173', '변증법적 논리학');
insert into tblDecimalCategory values (174, '174', '기호, 수리논리학');
insert into tblDecimalCategory values (175, '175', '오류');
insert into tblDecimalCategory values (176, '176', '삼단논법');
insert into tblDecimalCategory values (177, '177', '가설, 가정');
insert into tblDecimalCategory values (178, '178', '유추');
insert into tblDecimalCategory values (179, '179', '논증, 설득');
insert into tblDecimalCategory values (180, '180', '심리학');
insert into tblDecimalCategory values (181, '181', '심리학각론');
insert into tblDecimalCategory values (182, '182', '차이심리학');
insert into tblDecimalCategory values (183, '183', '발달심리학');
insert into tblDecimalCategory values (184, '184', '이상심리학');
insert into tblDecimalCategory values (185, '185', '생리심리학');
insert into tblDecimalCategory values (186, '186', '임상심리학');
insert into tblDecimalCategory values (187, '187', '심령연구 및 비학, 초심리학');
insert into tblDecimalCategory values (188, '188', '상법, 운명판단');
insert into tblDecimalCategory values (189, '189', '응용심리학 일반');
insert into tblDecimalCategory values (190, '190', '윤리학, 도덕철학');
insert into tblDecimalCategory values (191, '191', '일반윤리학 각론');
insert into tblDecimalCategory values (192, '192', '가정윤리');
insert into tblDecimalCategory values (193, '193', '국가 및 정치 윤리');
insert into tblDecimalCategory values (194, '194', '사회윤리');
insert into tblDecimalCategory values (195, '195', '직업윤리 일반');
insert into tblDecimalCategory values (196, '196', '오락 및 경기윤리');
insert into tblDecimalCategory values (197, '197', '성윤리 및 생식윤리');
insert into tblDecimalCategory values (198, '198', '소비윤리');
insert into tblDecimalCategory values (199, '199', '도덕훈, 교훈');
insert into tblDecimalCategory values (200, '200', '종교');
insert into tblDecimalCategory values (201, '201', '종교철학 및 종교사상');
insert into tblDecimalCategory values (202, '202', '잡저');
insert into tblDecimalCategory values (203, '203', '사전');
insert into tblDecimalCategory values (204, '204', '자연종교, 자연신학');
insert into tblDecimalCategory values (205, '205', '연속간행물');
insert into tblDecimalCategory values (206, '206', '학회, 단체, 협회, 기관, 회의');
insert into tblDecimalCategory values (207, '207', '지도법, 연구법 및 교육, 교육자료');
insert into tblDecimalCategory values (208, '208', '총서, 전집, 선집');
insert into tblDecimalCategory values (209, '209', '종교사');
insert into tblDecimalCategory values (210, '210', '비교종교');
insert into tblDecimalCategory values (211, '211', '교리');
insert into tblDecimalCategory values (212, '212', '종교창시자(교주) 및 제자');
insert into tblDecimalCategory values (213, '213', '경전, 성전');
insert into tblDecimalCategory values (214, '214', '종교신앙, 신앙록, 신앙생활, 수도생활');
insert into tblDecimalCategory values (215, '215', '선교, 포교, 전도, 교육활동');
insert into tblDecimalCategory values (216, '216', '종단, 교단(교당론)');
insert into tblDecimalCategory values (217, '217', '예배형식, 의식, 의례');
insert into tblDecimalCategory values (218, '218', '종파, 교파');
insert into tblDecimalCategory values (219, '219', '신화, 신화학');
insert into tblDecimalCategory values (220, '220', '불교');
insert into tblDecimalCategory values (221, '221', '불교교리');
insert into tblDecimalCategory values (222, '222', '부처, 보살, 불제자');
insert into tblDecimalCategory values (223, '223', '경전(불전, 불경, 대장경)');
insert into tblDecimalCategory values (224, '224', '종교신앙, 신앙록, 신앙생활');
insert into tblDecimalCategory values (225, '225', '포교, 교육, 교화활동');
insert into tblDecimalCategory values (226, '226', '사원론');
insert into tblDecimalCategory values (227, '227', '법회, 의식, 행사(의궤)');
insert into tblDecimalCategory values (228, '228', '종파');
insert into tblDecimalCategory values (229, '229', '라마교');
insert into tblDecimalCategory values (230, '230', '기독교');
insert into tblDecimalCategory values (231, '231', '기독교신학, 교의학(조직신학)');
insert into tblDecimalCategory values (232, '232', '예수 그리스도, 사도');
insert into tblDecimalCategory values (233, '233', '성서(성경)');
insert into tblDecimalCategory values (234, '234', '종교신앙, 신앙록, 신앙생활');
insert into tblDecimalCategory values (235, '235', '전도, 교육, 교화활동, 목회학');
insert into tblDecimalCategory values (236, '236', '교회론');
insert into tblDecimalCategory values (237, '237', '예배, 의식, 성례');
insert into tblDecimalCategory values (238, '238', '교파');
insert into tblDecimalCategory values (239, '239', '유대교(유태교)');
insert into tblDecimalCategory values (240, '240', '도교');
insert into tblDecimalCategory values (241, '241', '교의, 신선사상');
insert into tblDecimalCategory values (242, '242', '교조, 개조(장도릉)');
insert into tblDecimalCategory values (243, '243', '도장');
insert into tblDecimalCategory values (244, '244', '신앙록, 신앙생활');
insert into tblDecimalCategory values (245, '245', '포교, 전도, 교육, 교육활동');
insert into tblDecimalCategory values (246, '246', '사원론(도관)');
insert into tblDecimalCategory values (247, '247', '행사, 법술');
insert into tblDecimalCategory values (248, '248', '교파');
insert into tblDecimalCategory values (249, '249', '미사용');
insert into tblDecimalCategory values (250, '250', '천도교');
insert into tblDecimalCategory values (251, '251', '교리, 교의');
insert into tblDecimalCategory values (252, '252', '창시자(교주) 및 제자');
insert into tblDecimalCategory values (253, '253', '경전, 성전');
insert into tblDecimalCategory values (254, '254', '신앙록, 신앙생활, 수도생활');
insert into tblDecimalCategory values (255, '255', '선교, 포교, 전도, 교육활동');
insert into tblDecimalCategory values (256, '256', '종단, 교단');
insert into tblDecimalCategory values (257, '257', '예배형식, 의식, 의례');
insert into tblDecimalCategory values (258, '258', '동학교분파');
insert into tblDecimalCategory values (259, '259', '단군교, 대종교');
insert into tblDecimalCategory values (260, '260', '미사용');
insert into tblDecimalCategory values (261, '261', '미사용');
insert into tblDecimalCategory values (262, '262', '미사용');
insert into tblDecimalCategory values (263, '263', '미사용');
insert into tblDecimalCategory values (264, '264', '미사용');
insert into tblDecimalCategory values (265, '265', '미사용');
insert into tblDecimalCategory values (266, '266', '미사용');
insert into tblDecimalCategory values (267, '267', '미사용');
insert into tblDecimalCategory values (268, '268', '미사용');
insert into tblDecimalCategory values (269, '269', '미사용');
insert into tblDecimalCategory values (270, '270', '힌두교, 브라만교');
insert into tblDecimalCategory values (271, '271', '교리, 교의');
insert into tblDecimalCategory values (272, '272', '창시자(교주)및 제자');
insert into tblDecimalCategory values (273, '273', '경전, 성전');
insert into tblDecimalCategory values (274, '274', '신앙록, 신앙생활, 수도생활');
insert into tblDecimalCategory values (275, '275', '선교, 포교, 전도, 교육활동');
insert into tblDecimalCategory values (276, '276', '종단, 교단');
insert into tblDecimalCategory values (277, '277', '예배형식, 의식, 의례');
insert into tblDecimalCategory values (278, '278', '종파, 교파');
insert into tblDecimalCategory values (279, '279', '자이나교');
insert into tblDecimalCategory values (280, '280', '이슬람교(회교)');
insert into tblDecimalCategory values (281, '281', '교리, 교의');
insert into tblDecimalCategory values (282, '282', '창시자(교주) 및 제자');
insert into tblDecimalCategory values (283, '283', '경전, 성전');
insert into tblDecimalCategory values (284, '284', '신앙록, 신앙생활, 수도생활');
insert into tblDecimalCategory values (285, '285', '선교, 포교, 전도, 교육활동');
insert into tblDecimalCategory values (286, '286', '종단, 교단');
insert into tblDecimalCategory values (287, '287', '예배형식, 의식, 의례');
insert into tblDecimalCategory values (288, '288', '종파, 교파');
insert into tblDecimalCategory values (289, '289', '조로아스터교(요교, 배화교)');
insert into tblDecimalCategory values (290, '290', '기타 제종교');
insert into tblDecimalCategory values (291, '291', '아시아');
insert into tblDecimalCategory values (292, '292', '유럽');
insert into tblDecimalCategory values (293, '293', '아프리카');
insert into tblDecimalCategory values (294, '294', '북아메리카');
insert into tblDecimalCategory values (295, '295', '남아메리카');
insert into tblDecimalCategory values (296, '296', '오세아니아, 양극지방');
insert into tblDecimalCategory values (297, '297', '미사용');
insert into tblDecimalCategory values (298, '298', '미사용');
insert into tblDecimalCategory values (299, '299', '기타 다른 기원의 종교');
insert into tblDecimalCategory values (300, '300', '사회과학');
insert into tblDecimalCategory values (301, '301', '사회사상');
insert into tblDecimalCategory values (302, '302', '잡저');
insert into tblDecimalCategory values (303, '303', '사전');
insert into tblDecimalCategory values (304, '304', '강연집, 수필집, 연설문집');
insert into tblDecimalCategory values (305, '305', '연속간행물');
insert into tblDecimalCategory values (306, '306', '학회, 단체, 협회, 기관, 회의');
insert into tblDecimalCategory values (307, '307', '연구법, 연구방법 및 교육, 교육자료');
insert into tblDecimalCategory values (308, '308', '총서, 전집, 선집');
insert into tblDecimalCategory values (309, '309', '사회·문화 사정');
insert into tblDecimalCategory values (310, '310', '통계자료');
insert into tblDecimalCategory values (311, '311', '아시아');
insert into tblDecimalCategory values (312, '312', '유럽');
insert into tblDecimalCategory values (313, '313', '아프리카');
insert into tblDecimalCategory values (314, '314', '북아메리카');
insert into tblDecimalCategory values (315, '315', '남아메리카');
insert into tblDecimalCategory values (316, '316', '오세아니아, 양극지방');
insert into tblDecimalCategory values (317, '317', '일반지역');
insert into tblDecimalCategory values (318, '318', '미사용');
insert into tblDecimalCategory values (319, '319', '인구통계');
insert into tblDecimalCategory values (320, '320', '경제학');
insert into tblDecimalCategory values (321, '321', '경제각론');
insert into tblDecimalCategory values (322, '322', '경제정책');
insert into tblDecimalCategory values (323, '323', '산업경제 일반');
insert into tblDecimalCategory values (324, '324', '기업경제');
insert into tblDecimalCategory values (325, '325', '경영');
insert into tblDecimalCategory values (326, '326', '상업, 교통, 통신');
insert into tblDecimalCategory values (327, '327', '금융');
insert into tblDecimalCategory values (328, '328', '보험');
insert into tblDecimalCategory values (329, '329', '재정');
insert into tblDecimalCategory values (330, '330', '사회학, 사회문제');
insert into tblDecimalCategory values (331, '331', '사회학');
insert into tblDecimalCategory values (332, '332', '사회 조직 및 제도');
insert into tblDecimalCategory values (333, '333', '미사용');
insert into tblDecimalCategory values (334, '334', '사회문제');
insert into tblDecimalCategory values (335, '335', '생활문제');
insert into tblDecimalCategory values (336, '336', '미사용');
insert into tblDecimalCategory values (337, '337', '여성문제');
insert into tblDecimalCategory values (338, '338', '사회복지');
insert into tblDecimalCategory values (339, '339', '사회단체');
insert into tblDecimalCategory values (340, '340', '정치학');
insert into tblDecimalCategory values (341, '341', '국가형태');
insert into tblDecimalCategory values (342, '342', '국가와 개인 및 집단');
insert into tblDecimalCategory values (343, '343', '미사용');
insert into tblDecimalCategory values (344, '344', '선거');
insert into tblDecimalCategory values (345, '345', '입법');
insert into tblDecimalCategory values (346, '346', '정당');
insert into tblDecimalCategory values (347, '347', '미사용');
insert into tblDecimalCategory values (348, '348', '미사용');
insert into tblDecimalCategory values (349, '349', '외교, 국제 관계');
insert into tblDecimalCategory values (350, '350', '행정학');
insert into tblDecimalCategory values (351, '351', '아시아');
insert into tblDecimalCategory values (352, '352', '유럽');
insert into tblDecimalCategory values (353, '353', '아프리카');
insert into tblDecimalCategory values (354, '354', '북아메리카');
insert into tblDecimalCategory values (355, '355', '남아메리카');
insert into tblDecimalCategory values (356, '356', '오세아니아, 양극지방');
insert into tblDecimalCategory values (357, '357', '일반지역');
insert into tblDecimalCategory values (358, '358', '미사용');
insert into tblDecimalCategory values (359, '359', '지방자치 및 지방행정');
insert into tblDecimalCategory values (360, '360', '법률, 법학');
insert into tblDecimalCategory values (361, '361', '국제법');
insert into tblDecimalCategory values (362, '362', '헌법');
insert into tblDecimalCategory values (363, '363', '행정법');
insert into tblDecimalCategory values (364, '364', '형법');
insert into tblDecimalCategory values (365, '365', '민법');
insert into tblDecimalCategory values (366, '366', '상법');
insert into tblDecimalCategory values (367, '367', '사법제도 및 소송법');
insert into tblDecimalCategory values (368, '368', '기타 제법');
insert into tblDecimalCategory values (369, '369', '각국 법 및 예규');
insert into tblDecimalCategory values (370, '370', '교육학');
insert into tblDecimalCategory values (371, '371', '교육 정책 및 행정');
insert into tblDecimalCategory values (372, '372', '학교 행정 및 경영, 보건 및 교육 지도');
insert into tblDecimalCategory values (373, '373', '학습지도, 교육방법');
insert into tblDecimalCategory values (374, '374', '교육과정');
insert into tblDecimalCategory values (375, '375', '유아 및 초등 교육');
insert into tblDecimalCategory values (376, '376', '중등교육');
insert into tblDecimalCategory values (377, '377', '대학, 전문, 고등 교육');
insert into tblDecimalCategory values (378, '378', '평생교육');
insert into tblDecimalCategory values (379, '379', '특수교육');
insert into tblDecimalCategory values (380, '380', '풍속, 예절, 민속학');
insert into tblDecimalCategory values (381, '381', '의식주의 풍습');
insert into tblDecimalCategory values (382, '382', '연령별, 성별, 신분별 사회계층의 풍습');
insert into tblDecimalCategory values (383, '383', '사회생활의 풍습');
insert into tblDecimalCategory values (384, '384', '관혼상제');
insert into tblDecimalCategory values (385, '385', '예절');
insert into tblDecimalCategory values (386, '386', '축제, 세시풍속');
insert into tblDecimalCategory values (387, '387', '미사용');
insert into tblDecimalCategory values (388, '388', '민속학');
insert into tblDecimalCategory values (389, '389', '문화인류학');
insert into tblDecimalCategory values (390, '390', '국방, 군사학');
insert into tblDecimalCategory values (391, '391', '군사행정');
insert into tblDecimalCategory values (392, '392', '전략, 전술');
insert into tblDecimalCategory values (393, '393', '군사 교육 및 훈련');
insert into tblDecimalCategory values (394, '394', '군사 시설 및 장비');
insert into tblDecimalCategory values (395, '395', '군특수기술근무');
insert into tblDecimalCategory values (396, '396', '육군');
insert into tblDecimalCategory values (397, '397', '해군');
insert into tblDecimalCategory values (398, '398', '공군');
insert into tblDecimalCategory values (399, '399', '고대병법');
insert into tblDecimalCategory values (400, '400', '자연과학');
insert into tblDecimalCategory values (401, '401', '철학 및 이론');
insert into tblDecimalCategory values (402, '402', '잡저(편람, 제표, 서지, 인명록)');
insert into tblDecimalCategory values (403, '403', '사전, 백과사전');
insert into tblDecimalCategory values (404, '404', '강연집, 수필집, 연설문집');
insert into tblDecimalCategory values (405, '405', '연속간행물');
insert into tblDecimalCategory values (406, '406', '학회, 단체, 기관, 회의');
insert into tblDecimalCategory values (407, '407', '지도법, 연구법 및 교육, 교육자료');
insert into tblDecimalCategory values (408, '408', '전집, 총서');
insert into tblDecimalCategory values (409, '409', '과학사');
insert into tblDecimalCategory values (410, '410', '수학');
insert into tblDecimalCategory values (411, '411', '산수');
insert into tblDecimalCategory values (412, '412', '대수학');
insert into tblDecimalCategory values (413, '413', '통계학');
insert into tblDecimalCategory values (414, '414', '해석학');
insert into tblDecimalCategory values (415, '415', '기하학');
insert into tblDecimalCategory values (416, '416', '위상수학');
insert into tblDecimalCategory values (417, '417', '삼각법');
insert into tblDecimalCategory values (418, '418', '해석기하학');
insert into tblDecimalCategory values (419, '419', '기타 산법');
insert into tblDecimalCategory values (420, '420', '물리학');
insert into tblDecimalCategory values (421, '421', '고체역학');
insert into tblDecimalCategory values (422, '422', '유체역학');
insert into tblDecimalCategory values (423, '423', '기체역학');
insert into tblDecimalCategory values (424, '424', '음향학, 진동학');
insert into tblDecimalCategory values (425, '425', '광학');
insert into tblDecimalCategory values (426, '426', '열학');
insert into tblDecimalCategory values (427, '427', '전기학 및 전자학');
insert into tblDecimalCategory values (428, '428', '자기');
insert into tblDecimalCategory values (429, '429', '현대물리학');
insert into tblDecimalCategory values (430, '430', '화학');
insert into tblDecimalCategory values (431, '431', '이론화학과 물리화학');
insert into tblDecimalCategory values (432, '432', '화학실험실, 기기, 시설');
insert into tblDecimalCategory values (433, '433', '분석화학');
insert into tblDecimalCategory values (434, '434', '합성화학 일반');
insert into tblDecimalCategory values (435, '435', '무기화학');
insert into tblDecimalCategory values (436, '436', '금속원소와 그 화합물');
insert into tblDecimalCategory values (437, '437', '유기화학');
insert into tblDecimalCategory values (438, '438', '고리형화합물');
insert into tblDecimalCategory values (439, '439', '고분자화합물과 기타 유기물');
insert into tblDecimalCategory values (440, '440', '천문학');
insert into tblDecimalCategory values (441, '441', '이론천문학');
insert into tblDecimalCategory values (442, '442', '실지 천문학');
insert into tblDecimalCategory values (443, '443', '기술천문학');
insert into tblDecimalCategory values (444, '444', '미사용');
insert into tblDecimalCategory values (445, '445', '지구');
insert into tblDecimalCategory values (446, '446', '측지학');
insert into tblDecimalCategory values (447, '447', '항해천문학');
insert into tblDecimalCategory values (448, '448', '역법, 측시법');
insert into tblDecimalCategory values (449, '449', '각국의 역');
insert into tblDecimalCategory values (450, '450', '지학');
insert into tblDecimalCategory values (451, '451', '지구물리학');
insert into tblDecimalCategory values (452, '452', '지형학');
insert into tblDecimalCategory values (453, '453', '기상학, 기후학');
insert into tblDecimalCategory values (454, '454', '해양학');
insert into tblDecimalCategory values (455, '455', '구조지질학');
insert into tblDecimalCategory values (456, '456', '지사학');
insert into tblDecimalCategory values (457, '457', '고생물학(화석학)');
insert into tblDecimalCategory values (458, '458', '응용지질학 일반 및 광상학');
insert into tblDecimalCategory values (459, '459', '암석학');
insert into tblDecimalCategory values (460, '460', '광물학');
insert into tblDecimalCategory values (461, '461', '원소광물');
insert into tblDecimalCategory values (462, '462', '황화광물');
insert into tblDecimalCategory values (463, '463', '할로겐화광물');
insert into tblDecimalCategory values (464, '464', '산화광물');
insert into tblDecimalCategory values (465, '465', '규산 및 규산염광물');
insert into tblDecimalCategory values (466, '466', '기타 산화물을 포함한 광물');
insert into tblDecimalCategory values (467, '467', '유기광물');
insert into tblDecimalCategory values (468, '468', '미사용');
insert into tblDecimalCategory values (469, '469', '결정학');
insert into tblDecimalCategory values (470, '470', '생명과학');
insert into tblDecimalCategory values (471, '471', '인류학');
insert into tblDecimalCategory values (472, '472', '생물학');
insert into tblDecimalCategory values (473, '473', '생명론, 생물철학');
insert into tblDecimalCategory values (474, '474', '세포학(세포생물학)');
insert into tblDecimalCategory values (475, '475', '미생물학');
insert into tblDecimalCategory values (476, '476', '생물진화');
insert into tblDecimalCategory values (477, '477', '생물지리학');
insert into tblDecimalCategory values (478, '478', '현미경 및 현미경검사법 일반');
insert into tblDecimalCategory values (479, '479', '생물 채집 및 보존');
insert into tblDecimalCategory values (480, '480', '식물학');
insert into tblDecimalCategory values (481, '481', '일반 식물학');
insert into tblDecimalCategory values (482, '482', '은화식물');
insert into tblDecimalCategory values (483, '483', '엽상식물');
insert into tblDecimalCategory values (484, '484', '조균류');
insert into tblDecimalCategory values (485, '485', '현화식물, 종자식물');
insert into tblDecimalCategory values (486, '486', '나자식물');
insert into tblDecimalCategory values (487, '487', '피자식물');
insert into tblDecimalCategory values (488, '488', '단자엽식물');
insert into tblDecimalCategory values (489, '489', '쌍자엽식물');
insert into tblDecimalCategory values (490, '490', '동물학');
insert into tblDecimalCategory values (491, '491', '일반 동물학');
insert into tblDecimalCategory values (492, '492', '무척추동물');
insert into tblDecimalCategory values (493, '493', '원생동물, 해면동물, 자포동물, 선형동물');
insert into tblDecimalCategory values (494, '494', '연체동물, 의연체동물');
insert into tblDecimalCategory values (495, '495', '절지동물, 곤충류');
insert into tblDecimalCategory values (496, '496', '척삭(척색)동물');
insert into tblDecimalCategory values (497, '497', '어류, 양서류, 파충류');
insert into tblDecimalCategory values (498, '498', '조류');
insert into tblDecimalCategory values (499, '499', '포유류');
insert into tblDecimalCategory values (500, '500', '기술과학');
insert into tblDecimalCategory values (501, '501', '기술 철학 및 이론');
insert into tblDecimalCategory values (502, '502', '잡저');
insert into tblDecimalCategory values (503, '503', '사전, 백과사전, 용어사전');
insert into tblDecimalCategory values (504, '504', '강연집, 수필집, 연설문집');
insert into tblDecimalCategory values (505, '505', '연속간행물');
insert into tblDecimalCategory values (506, '506', '학회, 단체, 기관, 회의');
insert into tblDecimalCategory values (507, '507', '연구법 및 교육지도법');
insert into tblDecimalCategory values (508, '508', '전집, 총서');
insert into tblDecimalCategory values (509, '509', '기술사');
insert into tblDecimalCategory values (510, '510', '의학');
insert into tblDecimalCategory values (511, '511', '기초의학');
insert into tblDecimalCategory values (512, '512', '임상의학 일반');
insert into tblDecimalCategory values (513, '513', '내과학');
insert into tblDecimalCategory values (514, '514', '외과');
insert into tblDecimalCategory values (515, '515', '치과의학, 이비인후과학, 안과학 및 기타 임상의학');
insert into tblDecimalCategory values (516, '516', '산부인과, 소아과학');
insert into tblDecimalCategory values (517, '517', '건강증진, 공중보건 및 예방의학');
insert into tblDecimalCategory values (518, '518', '약학');
insert into tblDecimalCategory values (519, '519', '한의학');
insert into tblDecimalCategory values (520, '520', '농업, 농학');
insert into tblDecimalCategory values (521, '521', '농업기초학');
insert into tblDecimalCategory values (522, '522', '농업경제');
insert into tblDecimalCategory values (523, '523', '재배 및 보호');
insert into tblDecimalCategory values (524, '524', '작물학');
insert into tblDecimalCategory values (525, '525', '원예');
insert into tblDecimalCategory values (526, '526', '임학, 임업');
insert into tblDecimalCategory values (527, '527', '축산학');
insert into tblDecimalCategory values (528, '528', '수의학');
insert into tblDecimalCategory values (529, '529', '수산업, 생물자원의 보호, 수렵업');
insert into tblDecimalCategory values (530, '530', '공학, 공업일반, 토목공학, 환경공학');
insert into tblDecimalCategory values (531, '531', '토목공학');
insert into tblDecimalCategory values (532, '532', '토목역학, 토목재료');
insert into tblDecimalCategory values (533, '533', '측량');
insert into tblDecimalCategory values (534, '534', '도로공학');
insert into tblDecimalCategory values (535, '535', '철도공학');
insert into tblDecimalCategory values (536, '536', '교량공학');
insert into tblDecimalCategory values (537, '537', '수리공학');
insert into tblDecimalCategory values (538, '538', '항만공학');
insert into tblDecimalCategory values (539, '539', '위생, 도시, 환경 공학');
insert into tblDecimalCategory values (540, '540', '건축, 건축학');
insert into tblDecimalCategory values (541, '541', '건축재료');
insert into tblDecimalCategory values (542, '542', '건축 시공 및 적산');
insert into tblDecimalCategory values (543, '543', '구조역학 및 건축일반구조');
insert into tblDecimalCategory values (544, '544', '친환경건축 및 특정목적건축');
insert into tblDecimalCategory values (545, '545', '건물 세부구조');
insert into tblDecimalCategory values (546, '546', '건축 환경, 설비, 배관 및 파이프 부설');
insert into tblDecimalCategory values (547, '547', '난방, 환기 및 공기조화 공학');
insert into tblDecimalCategory values (548, '548', '건축마감 및 인테리어');
insert into tblDecimalCategory values (549, '549', '각종 건물');
insert into tblDecimalCategory values (550, '550', '기계공학');
insert into tblDecimalCategory values (551, '551', '기계 역학, 요소 및 설계');
insert into tblDecimalCategory values (552, '552', '공구와 가공장비');
insert into tblDecimalCategory values (553, '553', '열공학과 원동기');
insert into tblDecimalCategory values (554, '554', '유체역학, 공기역학, 진동학');
insert into tblDecimalCategory values (555, '555', '정밀기계');
insert into tblDecimalCategory values (556, '556', '자동차공학');
insert into tblDecimalCategory values (557, '557', '철도차량, 기관차');
insert into tblDecimalCategory values (558, '558', '항공우주공학, 우주항법학');
insert into tblDecimalCategory values (559, '559', '기타 공학');
insert into tblDecimalCategory values (560, '560', '전기공학, 통신공학, 전자공학');
insert into tblDecimalCategory values (561, '561', '전기 회로, 계측, 재료');
insert into tblDecimalCategory values (562, '562', '전기 기계 및 기구');
insert into tblDecimalCategory values (563, '563', '발전');
insert into tblDecimalCategory values (564, '564', '송전, 배전');
insert into tblDecimalCategory values (565, '565', '전등, 조명, 전열');
insert into tblDecimalCategory values (566, '566', '미사용');
insert into tblDecimalCategory values (567, '567', '통신공학');
insert into tblDecimalCategory values (568, '568', '무선공학');
insert into tblDecimalCategory values (569, '569', '전자공학');
insert into tblDecimalCategory values (570, '570', '화학공학');
insert into tblDecimalCategory values (571, '571', '공업화학약품');
insert into tblDecimalCategory values (572, '572', '폭발물, 연료 공업');
insert into tblDecimalCategory values (573, '573', '음료기술');
insert into tblDecimalCategory values (574, '574', '식품공학');
insert into tblDecimalCategory values (575, '575', '납, 유지, 석유, 가스 공업');
insert into tblDecimalCategory values (576, '576', '요업 및 관련공업');
insert into tblDecimalCategory values (577, '577', '세탁, 염색 및 관련공업');
insert into tblDecimalCategory values (578, '578', '고분자화학공업');
insert into tblDecimalCategory values (579, '579', '기타 유기화학공업');
insert into tblDecimalCategory values (580, '580', '제조업');
insert into tblDecimalCategory values (581, '581', '금속 제조 및 가공업');
insert into tblDecimalCategory values (582, '582', '철 및 강철 제품');
insert into tblDecimalCategory values (583, '583', '철기류 및 소규모철공');
insert into tblDecimalCategory values (584, '584', '제재업, 목공업, 목제품');
insert into tblDecimalCategory values (585, '585', '피혁 및 모피 공업');
insert into tblDecimalCategory values (586, '586', '펄프, 종이 및 관련공업');
insert into tblDecimalCategory values (587, '587', '직물 및 섬유공업');
insert into tblDecimalCategory values (588, '588', '의류제조');
insert into tblDecimalCategory values (589, '589', '소형상품제조');
insert into tblDecimalCategory values (590, '590', '생활과학');
insert into tblDecimalCategory values (591, '591', '가정관리 및 가정생활');
insert into tblDecimalCategory values (592, '592', '의복');
insert into tblDecimalCategory values (593, '593', '몸치장(몸단장), 화장');
insert into tblDecimalCategory values (594, '594', '식품과 음료');
insert into tblDecimalCategory values (595, '595', '주택관리 및 가정설비');
insert into tblDecimalCategory values (596, '596', '공동주거용 주택 시설관리');
insert into tblDecimalCategory values (597, '597', '가정위생');
insert into tblDecimalCategory values (598, '598', '육아');
insert into tblDecimalCategory values (599, '599', '미사용');
insert into tblDecimalCategory values (600, '600', '예술');
insert into tblDecimalCategory values (601, '601', '미술이론, 미학');
insert into tblDecimalCategory values (602, '602', '미술 재료 및 기법');
insert into tblDecimalCategory values (603, '603', '미술 용어사전, 백과사전');
insert into tblDecimalCategory values (604, '604', '미술의 주제');
insert into tblDecimalCategory values (605, '605', '미술연속간행물');
insert into tblDecimalCategory values (606, '606', '미술분야의 학회, 단체, 기관, 회의');
insert into tblDecimalCategory values (607, '607', '미술의 지도법, 연구법 및 교육, 교육자료');
insert into tblDecimalCategory values (608, '608', '미술 전집, 총서');
insert into tblDecimalCategory values (609, '609', '미술사');
insert into tblDecimalCategory values (610, '610', '미사용');
insert into tblDecimalCategory values (611, '611', '미사용');
insert into tblDecimalCategory values (612, '612', '미사용');
insert into tblDecimalCategory values (613, '613', '미사용');
insert into tblDecimalCategory values (614, '614', '미사용');
insert into tblDecimalCategory values (615, '615', '미사용');
insert into tblDecimalCategory values (616, '616', '미사용');
insert into tblDecimalCategory values (617, '617', '미사용');
insert into tblDecimalCategory values (618, '618', '미사용');
insert into tblDecimalCategory values (619, '619', '미사용');
insert into tblDecimalCategory values (620, '620', '조각, 조형미술');
insert into tblDecimalCategory values (621, '621', '미사용');
insert into tblDecimalCategory values (622, '622', '조소 재료 및 기법');
insert into tblDecimalCategory values (623, '623', '목조');
insert into tblDecimalCategory values (624, '624', '석조');
insert into tblDecimalCategory values (625, '625', '금동조');
insert into tblDecimalCategory values (626, '626', '점토조소, 소조');
insert into tblDecimalCategory values (627, '627', '기타 재료');
insert into tblDecimalCategory values (628, '628', '전각, 인장');
insert into tblDecimalCategory values (629, '629', '제상');
insert into tblDecimalCategory values (630, '630', '공예');
insert into tblDecimalCategory values (631, '631', '도자공예, 유리공예');
insert into tblDecimalCategory values (632, '632', '금속공예');
insert into tblDecimalCategory values (633, '633', '보석, 갑각, 패류, 알 공예');
insert into tblDecimalCategory values (634, '634', '목, 죽, 화훼, 왕골 공예');
insert into tblDecimalCategory values (635, '635', '칠공예');
insert into tblDecimalCategory values (636, '636', '염직물공예, 섬유공예');
insert into tblDecimalCategory values (637, '637', '고무, 플라스틱공예');
insert into tblDecimalCategory values (638, '638', '미술가구');
insert into tblDecimalCategory values (639, '639', '미사용');
insert into tblDecimalCategory values (640, '640', '서예');
insert into tblDecimalCategory values (641, '641', '한자서체');
insert into tblDecimalCategory values (642, '642', '한자서법');
insert into tblDecimalCategory values (643, '643', '한글서체');
insert into tblDecimalCategory values (644, '644', '기타 서법');
insert into tblDecimalCategory values (645, '645', '미사용');
insert into tblDecimalCategory values (646, '646', '펜습자');
insert into tblDecimalCategory values (647, '647', '낙관, 수결(서명)');
insert into tblDecimalCategory values (648, '648', '서보, 서첩, 법첩');
insert into tblDecimalCategory values (649, '649', '문방구');
insert into tblDecimalCategory values (650, '650', '회화, 도화, 디자인');
insert into tblDecimalCategory values (651, '651', '채색 이론 및 실제');
insert into tblDecimalCategory values (652, '652', '회화의 재료 및 기법');
insert into tblDecimalCategory values (653, '653', '시대별 및 국별 회화');
insert into tblDecimalCategory values (654, '654', '주제별 회화');
insert into tblDecimalCategory values (655, '655', '미사용');
insert into tblDecimalCategory values (656, '656', '소묘, 도화');
insert into tblDecimalCategory values (657, '657', '만화, 삽화');
insert into tblDecimalCategory values (658, '658', '디자인');
insert into tblDecimalCategory values (659, '659', '판화');
insert into tblDecimalCategory values (660, '660', '사진예술');
insert into tblDecimalCategory values (661, '661', '사진기계, 재료');
insert into tblDecimalCategory values (662, '662', '사진촬영기술');
insert into tblDecimalCategory values (663, '663', '음화처리');
insert into tblDecimalCategory values (664, '664', '양화처리(인화)');
insert into tblDecimalCategory values (665, '665', '미사용');
insert into tblDecimalCategory values (666, '666', '특수사진술');
insert into tblDecimalCategory values (667, '667', '사진응용');
insert into tblDecimalCategory values (668, '668', '사진집');
insert into tblDecimalCategory values (669, '669', '미사용');
insert into tblDecimalCategory values (670, '670', '음악');
insert into tblDecimalCategory values (671, '671', '음악 이론 및 기법');
insert into tblDecimalCategory values (672, '672', '종교음악');
insert into tblDecimalCategory values (673, '673', '성악');
insert into tblDecimalCategory values (674, '674', '극음악, 오페라');
insert into tblDecimalCategory values (675, '675', '기악합주');
insert into tblDecimalCategory values (676, '676', '건반악기 및 타악기');
insert into tblDecimalCategory values (677, '677', '현악기');
insert into tblDecimalCategory values (678, '678', '관악기(취주악기)');
insert into tblDecimalCategory values (679, '679', '한국음악 및 동양전통음악');
insert into tblDecimalCategory values (680, '680', '공연예술, 매체예술');
insert into tblDecimalCategory values (681, '681', '극장, 제작, 연출, 연기');
insert into tblDecimalCategory values (682, '682', '연희');
insert into tblDecimalCategory values (683, '683', '미사용');
insert into tblDecimalCategory values (684, '684', '각종 연극');
insert into tblDecimalCategory values (685, '685', '무용, 발레');
insert into tblDecimalCategory values (686, '686', '라디오극(방송극) 및 음성(소리)매체 예술');
insert into tblDecimalCategory values (687, '687', '텔레비전극 및 시청각매체 방송 예술');
insert into tblDecimalCategory values (688, '688', '영화');
insert into tblDecimalCategory values (689, '689', '대중연예');
insert into tblDecimalCategory values (690, '690', '오락, 스포츠');
insert into tblDecimalCategory values (691, '691', '오락');
insert into tblDecimalCategory values (692, '692', '체육학, 스포츠');
insert into tblDecimalCategory values (693, '693', '체조, 놀이');
insert into tblDecimalCategory values (694, '694', '육상경기');
insert into tblDecimalCategory values (695, '695', '구기');
insert into tblDecimalCategory values (696, '696', '수상경기, 공중경기');
insert into tblDecimalCategory values (697, '697', '동계스포츠');
insert into tblDecimalCategory values (698, '698', '무예 및 기타 경기');
insert into tblDecimalCategory values (699, '699', '기타 오락 및 레저스포츠');
insert into tblDecimalCategory values (700, '700', '언어');
insert into tblDecimalCategory values (701, '701', '언어학');
insert into tblDecimalCategory values (702, '702', '잡저');
insert into tblDecimalCategory values (703, '703', '사전');
insert into tblDecimalCategory values (704, '704', '강연집, 수필집');
insert into tblDecimalCategory values (705, '705', '연속간행물');
insert into tblDecimalCategory values (706, '706', '학회, 단체, 기관, 회의');
insert into tblDecimalCategory values (707, '707', '지도법, 연구법 및 교육, 교육자료');
insert into tblDecimalCategory values (708, '708', '전집, 총서');
insert into tblDecimalCategory values (709, '709', '언어사 및 언어정책, 언어행정');
insert into tblDecimalCategory values (710, '710', '한국어');
insert into tblDecimalCategory values (711, '711', '음운, 음성, 문자');
insert into tblDecimalCategory values (712, '712', '어원, 어의');
insert into tblDecimalCategory values (713, '713', '사전');
insert into tblDecimalCategory values (714, '714', '어휘');
insert into tblDecimalCategory values (715, '715', '문법');
insert into tblDecimalCategory values (716, '716', '작문');
insert into tblDecimalCategory values (717, '717', '독본, 해석, 회화');
insert into tblDecimalCategory values (718, '718', '방언(사투리)');
insert into tblDecimalCategory values (719, '719', '미사용');
insert into tblDecimalCategory values (720, '720', '중국어');
insert into tblDecimalCategory values (721, '721', '음운, 음성, 문자');
insert into tblDecimalCategory values (722, '722', '어원, 어의');
insert into tblDecimalCategory values (723, '723', '사전');
insert into tblDecimalCategory values (724, '724', '어휘');
insert into tblDecimalCategory values (725, '725', '문법, 어법');
insert into tblDecimalCategory values (726, '726', '작문');
insert into tblDecimalCategory values (727, '727', '독본, 해석, 회화');
insert into tblDecimalCategory values (728, '728', '방언(사투리)');
insert into tblDecimalCategory values (729, '729', '미사용');
insert into tblDecimalCategory values (730, '730', '일본어 및 기타 아시아 제어');
insert into tblDecimalCategory values (731, '731', '음운, 음성 문자');
insert into tblDecimalCategory values (732, '732', '어원, 어의');
insert into tblDecimalCategory values (733, '733', '사전');
insert into tblDecimalCategory values (734, '734', '어휘');
insert into tblDecimalCategory values (735, '735', '문법, 어법');
insert into tblDecimalCategory values (736, '736', '작문');
insert into tblDecimalCategory values (737, '737', '독본, 해석, 회화');
insert into tblDecimalCategory values (738, '738', '방언(사투리)');
insert into tblDecimalCategory values (739, '739', '기타 아시아 제어');
insert into tblDecimalCategory values (740, '740', '영어');
insert into tblDecimalCategory values (741, '741', '음운, 음성, 문자');
insert into tblDecimalCategory values (742, '742', '어원, 어의');
insert into tblDecimalCategory values (743, '743', '사전');
insert into tblDecimalCategory values (744, '744', '어휘');
insert into tblDecimalCategory values (745, '745', '문법');
insert into tblDecimalCategory values (746, '746', '작문');
insert into tblDecimalCategory values (747, '747', '독본, 해석, 회화');
insert into tblDecimalCategory values (748, '748', '방언(사투리)');
insert into tblDecimalCategory values (749, '749', '앵글로색슨어');
insert into tblDecimalCategory values (750, '750', '독일어');
insert into tblDecimalCategory values (751, '751', '음운, 음성, 문자');
insert into tblDecimalCategory values (752, '752', '어원, 어의');
insert into tblDecimalCategory values (753, '753', '사전');
insert into tblDecimalCategory values (754, '754', '어휘');
insert into tblDecimalCategory values (755, '755', '문법');
insert into tblDecimalCategory values (756, '756', '작문');
insert into tblDecimalCategory values (757, '757', '독본, 해석, 회화');
insert into tblDecimalCategory values (758, '758', '방언(사투리)');
insert into tblDecimalCategory values (759, '759', '기타 게르만어파');
insert into tblDecimalCategory values (760, '760', '프랑스어');
insert into tblDecimalCategory values (761, '761', '음운, 음성, 문자');
insert into tblDecimalCategory values (762, '762', '어원, 어의');
insert into tblDecimalCategory values (763, '763', '사전');
insert into tblDecimalCategory values (764, '764', '어휘');
insert into tblDecimalCategory values (765, '765', '문법');
insert into tblDecimalCategory values (766, '766', '작문');
insert into tblDecimalCategory values (767, '767', '독본, 해석, 회화');
insert into tblDecimalCategory values (768, '768', '방언(사투리)');
insert into tblDecimalCategory values (769, '769', '프로방스어');
insert into tblDecimalCategory values (770, '770', '스페인어 및 포르투갈어');
insert into tblDecimalCategory values (771, '771', '음운, 음성, 문자');
insert into tblDecimalCategory values (772, '772', '어원, 어의');
insert into tblDecimalCategory values (773, '773', '사전');
insert into tblDecimalCategory values (774, '774', '어휘');
insert into tblDecimalCategory values (775, '775', '문법');
insert into tblDecimalCategory values (776, '776', '작문');
insert into tblDecimalCategory values (777, '777', '독본, 해석, 회화');
insert into tblDecimalCategory values (778, '778', '방언(사투리)');
insert into tblDecimalCategory values (779, '779', '포르투갈어');
insert into tblDecimalCategory values (780, '780', '이탈리아어');
insert into tblDecimalCategory values (781, '781', '음운, 음성, 문자');
insert into tblDecimalCategory values (782, '782', '어원, 어의');
insert into tblDecimalCategory values (783, '783', '사전');
insert into tblDecimalCategory values (784, '784', '어휘');
insert into tblDecimalCategory values (785, '785', '문법');
insert into tblDecimalCategory values (786, '786', '작문');
insert into tblDecimalCategory values (787, '787', '독본, 해석, 회화');
insert into tblDecimalCategory values (788, '788', '방언(사투리)');
insert into tblDecimalCategory values (789, '789', '루마니아어');
insert into tblDecimalCategory values (790, '790', '기타 제어');
insert into tblDecimalCategory values (791, '791', '미사용');
insert into tblDecimalCategory values (792, '792', '인도-유럽어족');
insert into tblDecimalCategory values (793, '793', '아프리카 제어');
insert into tblDecimalCategory values (794, '794', '북아메리카 인디언어');
insert into tblDecimalCategory values (795, '795', '남아메리카 인디언어');
insert into tblDecimalCategory values (796, '796', '오스트로네시아어족');
insert into tblDecimalCategory values (797, '797', '셈족어(셈어파)');
insert into tblDecimalCategory values (798, '798', '함족어(함어파)');
insert into tblDecimalCategory values (799, '799', '국제어(인공어) 및 기타 언어');
insert into tblDecimalCategory values (800, '800', '문학');
insert into tblDecimalCategory values (801, '801', '문학이론');
insert into tblDecimalCategory values (802, '802', '문장작법, 수사학');
insert into tblDecimalCategory values (803, '803', '사전, 사전[2]');
insert into tblDecimalCategory values (804, '804', '수필집, 강연집');
insert into tblDecimalCategory values (805, '805', '연속간행물');
insert into tblDecimalCategory values (806, '806', '학회, 단체, 기관, 회의');
insert into tblDecimalCategory values (807, '807', '지도법 및 연구법, 교육, 교육자료');
insert into tblDecimalCategory values (808, '808', '전집, 총서');
insert into tblDecimalCategory values (809, '809', '문학사, 평론');
insert into tblDecimalCategory values (810, '810', '한국문학');
insert into tblDecimalCategory values (811, '811', '시');
insert into tblDecimalCategory values (812, '812', '희곡');
insert into tblDecimalCategory values (813, '813', '소설');
insert into tblDecimalCategory values (814, '814', '수필');
insert into tblDecimalCategory values (815, '815', '연설, 웅변');
insert into tblDecimalCategory values (816, '816', '일기, 서간, 기행');
insert into tblDecimalCategory values (817, '817', '풍자 및 유머');
insert into tblDecimalCategory values (818, '818', '르포르타주 및 기타');
insert into tblDecimalCategory values (819, '819', '미사용');
insert into tblDecimalCategory values (820, '820', '중국문학');
insert into tblDecimalCategory values (821, '821', '시');
insert into tblDecimalCategory values (822, '822', '희곡');
insert into tblDecimalCategory values (823, '823', '소설');
insert into tblDecimalCategory values (824, '824', '수필');
insert into tblDecimalCategory values (825, '825', '연설, 웅변');
insert into tblDecimalCategory values (826, '826', '일기, 서간, 기행');
insert into tblDecimalCategory values (827, '827', '풍자 및 유머');
insert into tblDecimalCategory values (828, '828', '르포르타주 및 기타');
insert into tblDecimalCategory values (829, '829', '미사용');
insert into tblDecimalCategory values (830, '830', '일본문학 및 기타 아시아 제문학');
insert into tblDecimalCategory values (831, '831', '시');
insert into tblDecimalCategory values (832, '832', '희곡');
insert into tblDecimalCategory values (833, '833', '소설');
insert into tblDecimalCategory values (834, '834', '수필');
insert into tblDecimalCategory values (835, '835', '연설, 웅변');
insert into tblDecimalCategory values (836, '836', '일기, 서간, 기행');
insert into tblDecimalCategory values (837, '837', '풍자 및 유머');
insert into tblDecimalCategory values (838, '838', '르포르타주 및 기타');
insert into tblDecimalCategory values (839, '839', '기타 아시아 제문학');
insert into tblDecimalCategory values (840, '840', '영미문학');
insert into tblDecimalCategory values (841, '841', '시');
insert into tblDecimalCategory values (842, '842', '희곡');
insert into tblDecimalCategory values (843, '843', '소설');
insert into tblDecimalCategory values (844, '844', '수필');
insert into tblDecimalCategory values (845, '845', '연설, 웅변');
insert into tblDecimalCategory values (846, '846', '일기, 서간, 기행');
insert into tblDecimalCategory values (847, '847', '풍자 및 유머');
insert into tblDecimalCategory values (848, '848', '르포르타주 및 기타');
insert into tblDecimalCategory values (849, '849', ') 미국문학');
insert into tblDecimalCategory values (850, '850', '독일문학');
insert into tblDecimalCategory values (851, '851', '시');
insert into tblDecimalCategory values (852, '852', '희곡');
insert into tblDecimalCategory values (853, '853', '소설');
insert into tblDecimalCategory values (854, '854', '수필');
insert into tblDecimalCategory values (855, '855', '연설, 웅변');
insert into tblDecimalCategory values (856, '856', '일기, 서간, 기행');
insert into tblDecimalCategory values (857, '857', '풍자 및 유머');
insert into tblDecimalCategory values (858, '858', '르포르타주 및 기타');
insert into tblDecimalCategory values (859, '859', '기타 게르만문학[8]');
insert into tblDecimalCategory values (860, '860', '프랑스문학');
insert into tblDecimalCategory values (861, '861', '시');
insert into tblDecimalCategory values (862, '862', '희곡');
insert into tblDecimalCategory values (863, '863', '소설');
insert into tblDecimalCategory values (864, '864', '수필');
insert into tblDecimalCategory values (865, '865', '연설, 웅변');
insert into tblDecimalCategory values (866, '866', '일기, 서간, 기행');
insert into tblDecimalCategory values (867, '867', '풍자 및 유머');
insert into tblDecimalCategory values (868, '868', '르포르타주 및 기타');
insert into tblDecimalCategory values (869, '869', '프로방스문학');
insert into tblDecimalCategory values (870, '870', '스페인 및 포르투갈문학');
insert into tblDecimalCategory values (871, '871', '시');
insert into tblDecimalCategory values (872, '872', '희곡');
insert into tblDecimalCategory values (873, '873', '소설');
insert into tblDecimalCategory values (874, '874', '수필');
insert into tblDecimalCategory values (875, '875', '연설, 웅변');
insert into tblDecimalCategory values (876, '876', '일기, 서간, 기행');
insert into tblDecimalCategory values (877, '877', '풍자 및 유머');
insert into tblDecimalCategory values (878, '878', '르포르타주 및 기타');
insert into tblDecimalCategory values (879, '879', '포르투갈문학');
insert into tblDecimalCategory values (880, '880', '이탈리아문학');
insert into tblDecimalCategory values (881, '881', '시');
insert into tblDecimalCategory values (882, '882', '희곡');
insert into tblDecimalCategory values (883, '883', '소설');
insert into tblDecimalCategory values (884, '884', '수필');
insert into tblDecimalCategory values (885, '885', '연설, 웅변');
insert into tblDecimalCategory values (886, '886', '일기, 서간, 기행');
insert into tblDecimalCategory values (887, '887', '풍자 및 유머');
insert into tblDecimalCategory values (888, '888', '르포르타주 및 기타');
insert into tblDecimalCategory values (889, '889', '루마니아문학');
insert into tblDecimalCategory values (890, '890', '기타 제문학');
insert into tblDecimalCategory values (891, '891', '미사용');
insert into tblDecimalCategory values (892, '892', '인도-유럽계문학');
insert into tblDecimalCategory values (893, '893', '아프리카 제문학');
insert into tblDecimalCategory values (894, '894', '북아메리카 인디언문학');
insert into tblDecimalCategory values (895, '895', '남아메리카 인디언문학');
insert into tblDecimalCategory values (896, '896', '오스트로네시아문학');
insert into tblDecimalCategory values (897, '897', '셈족문학');
insert into tblDecimalCategory values (898, '898', '함족문학');
insert into tblDecimalCategory values (899, '899', '기타 문학');
insert into tblDecimalCategory values (900, '900', '역사');
insert into tblDecimalCategory values (901, '901', '역사 철학 및 이론');
insert into tblDecimalCategory values (902, '902', '역사보조학');
insert into tblDecimalCategory values (903, '903', '사전');
insert into tblDecimalCategory values (904, '904', '강연집, 사평');
insert into tblDecimalCategory values (905, '905', '연속간행물');
insert into tblDecimalCategory values (906, '906', '학회, 단체, 기관, 회의');
insert into tblDecimalCategory values (907, '907', '지도법, 연구법 및 교육, 교육자료');
insert into tblDecimalCategory values (908, '908', '전집, 총서');
insert into tblDecimalCategory values (909, '909', '세계사, 세계문화사');
insert into tblDecimalCategory values (910, '910', '아시아');
insert into tblDecimalCategory values (911, '911', '한국');
insert into tblDecimalCategory values (912, '912', '중국');
insert into tblDecimalCategory values (913, '913', '일본');
insert into tblDecimalCategory values (914, '914', '동남아시아');
insert into tblDecimalCategory values (915, '915', '인디아와 남부아시아');
insert into tblDecimalCategory values (916, '916', '중앙아시아');
insert into tblDecimalCategory values (917, '917', '시베리아');
insert into tblDecimalCategory values (918, '918', '서남아시아, 중동');
insert into tblDecimalCategory values (919, '919', '아라비아반도와 인접지역');
insert into tblDecimalCategory values (920, '920', '유럽');
insert into tblDecimalCategory values (921, '921', '고대 그리스(희랍고대사)');
insert into tblDecimalCategory values (922, '922', '고대 로마');
insert into tblDecimalCategory values (923, '923', '스칸디나비아');
insert into tblDecimalCategory values (924, '924', '영국, 아일랜드');
insert into tblDecimalCategory values (925, '925', '독일과 중앙유럽');
insert into tblDecimalCategory values (926, '926', '프랑스와 인접국가');
insert into tblDecimalCategory values (927, '927', '스페인과 인접국가');
insert into tblDecimalCategory values (928, '928', '이탈리아와 인접국가');
insert into tblDecimalCategory values (929, '929', '러시아와 동부유럽');
insert into tblDecimalCategory values (930, '930', '아프리카');
insert into tblDecimalCategory values (931, '931', '북아프리카');
insert into tblDecimalCategory values (932, '932', '미사용');
insert into tblDecimalCategory values (933, '933', '미사용');
insert into tblDecimalCategory values (934, '934', '서아프리카');
insert into tblDecimalCategory values (935, '935', '미사용');
insert into tblDecimalCategory values (936, '936', '중앙아프리카');
insert into tblDecimalCategory values (937, '937', '동아프리카');
insert into tblDecimalCategory values (938, '938', '남아프리카');
insert into tblDecimalCategory values (939, '939', '남인도양제도');
insert into tblDecimalCategory values (940, '940', '북아메리카');
insert into tblDecimalCategory values (941, '941', '캐나다');
insert into tblDecimalCategory values (942, '942', '미국(미합중국)');
insert into tblDecimalCategory values (943, '943', '멕시코');
insert into tblDecimalCategory values (944, '944', '중앙아메리카(중미제국)');
insert into tblDecimalCategory values (945, '945', '과테말라, 벨리즈, 엘살바도르');
insert into tblDecimalCategory values (946, '946', '온두라스');
insert into tblDecimalCategory values (947, '947', '니카라과');
insert into tblDecimalCategory values (948, '948', '코스타리카, 파나마');
insert into tblDecimalCategory values (949, '949', '서인도제도');
insert into tblDecimalCategory values (950, '950', '남아메리카');
insert into tblDecimalCategory values (951, '951', '콜롬비아');
insert into tblDecimalCategory values (952, '952', '베네수엘라와 기아나 지역');
insert into tblDecimalCategory values (953, '953', '브라질');
insert into tblDecimalCategory values (954, '954', '에콰도르');
insert into tblDecimalCategory values (955, '955', '페루');
insert into tblDecimalCategory values (956, '956', '볼리비아');
insert into tblDecimalCategory values (957, '957', '파라과이, 우루과이');
insert into tblDecimalCategory values (958, '958', '아르헨티나');
insert into tblDecimalCategory values (959, '959', '칠레');
insert into tblDecimalCategory values (960, '960', '오세아니아, 양극지방');
insert into tblDecimalCategory values (961, '961', '미사용');
insert into tblDecimalCategory values (962, '962', '오스트레일리아(호주)');
insert into tblDecimalCategory values (963, '963', '뉴질랜드');
insert into tblDecimalCategory values (964, '964', '파푸아뉴기니');
insert into tblDecimalCategory values (965, '965', '멜라네시아');
insert into tblDecimalCategory values (966, '966', '미크로네시아와 인접 국가');
insert into tblDecimalCategory values (967, '967', '폴리네시아와 하와이');
insert into tblDecimalCategory values (968, '968', '대서양제도');
insert into tblDecimalCategory values (969, '969', '양극지방');
insert into tblDecimalCategory values (970, '970', '미사용');
insert into tblDecimalCategory values (971, '971', '미사용');
insert into tblDecimalCategory values (972, '972', '미사용');
insert into tblDecimalCategory values (973, '973', '미사용');
insert into tblDecimalCategory values (974, '974', '미사용');
insert into tblDecimalCategory values (975, '975', '미사용');
insert into tblDecimalCategory values (976, '976', '미사용');
insert into tblDecimalCategory values (977, '977', '미사용');
insert into tblDecimalCategory values (978, '978', '미사용');
insert into tblDecimalCategory values (979, '979', '미사용');
insert into tblDecimalCategory values (980, '980', '지리');
insert into tblDecimalCategory values (981, '981', '아시아지리');
insert into tblDecimalCategory values (982, '982', '유럽지리');
insert into tblDecimalCategory values (983, '983', '아프리카지리');
insert into tblDecimalCategory values (984, '984', '북아메리카지리');
insert into tblDecimalCategory values (985, '985', '남아메리카지리');
insert into tblDecimalCategory values (986, '986', '오세아니아지리와 양극 지리');
insert into tblDecimalCategory values (987, '987', '지역구분 일반지리');
insert into tblDecimalCategory values (988, '988', '해양');
insert into tblDecimalCategory values (989, '989', '지도 및 지도책');
insert into tblDecimalCategory values (990, '990', '전기');
insert into tblDecimalCategory values (991, '991', '아시아전기');
insert into tblDecimalCategory values (992, '992', '유럽전기');
insert into tblDecimalCategory values (993, '993', '아프리카전기');
insert into tblDecimalCategory values (994, '994', '북아메리카전기');
insert into tblDecimalCategory values (995, '995', '남아메리카전기');
insert into tblDecimalCategory values (996, '996', '오세아니아와 양극 전기');
insert into tblDecimalCategory values (997, '997', '미사용');
insert into tblDecimalCategory values (998, '998', '주제별 전기');
insert into tblDecimalCategory values (999, '999', '계보, 족보');

select count(*) from tbldecimalcategory;
