insert into tblBook values (book_seq.nextVal, '보이지 않는 권력자: 미생물과 인간에 관하여', '빨간소금', '이재열', 425, 73, 0);
insert into tblBook values (book_seq.nextVal, '코스모스: 가능한 세계들', 'Yeondoo', '앤 드루얀 ', 446, 64, 0);
insert into tblBook values (book_seq.nextVal, '포토 아크, 새', '이터', '노아 스트리커 ', 458, 13, 0);
insert into tblBook values (book_seq.nextVal, '식물', '사이', 'DK 편집위원회 ', 482, 46, 0);
insert into tblBook values (book_seq.nextVal, '심리 원리', '쌤앤파커스', 'DK 편집위원회 ', 434, 32, 0);
insert into tblBook values (book_seq.nextVal, '과학의 품격', '파란 :파란미디어', '강양구', 453, 53, 0);
insert into tblBook values (book_seq.nextVal, '습지주의자', '이터', '김산하', 479, 26, 0);
insert into tblBook values (book_seq.nextVal, '화학이란 무엇인가', '스몰빅라이프 :스몰빅미디어', '피터 앳킨스  ', 438, 02, 0);
insert into tblBook values (book_seq.nextVal, '스타 토크', '버튼북스', '닐 디그래스 타이슨', 402, 38, 0);
insert into tblBook values (book_seq.nextVal, '명왕성 연대기', '피어오름', '닐 디그래스 타이슨 ', 484, 83, 0);
insert into tblBook values (book_seq.nextVal, '포토 아크', '동아엠앤비', '조엘 사토리 ', 473, 81, 0);
insert into tblBook values (book_seq.nextVal, '종의 기원', '로드북', '찰스 로버트 다윈 ', 490, 78, 0);
insert into tblBook values (book_seq.nextVal, '과학 수다 3: 대통령을 위한 뇌과학', '젤리판다', '이명현', 425, 93, 0);
insert into tblBook values (book_seq.nextVal, '과학 수다 4: 과학, 누구냐 넌?', '학연문화사', '이명현', 444, 28, 0);
insert into tblBook values (book_seq.nextVal, '아름다운 미생물 이야기', '리수', '김완기', 447, 19, 0);
insert into tblBook values (book_seq.nextVal, '침묵하는 우주', '한빛라이프', '폴 데이비스 ', 478, 95, 0);
insert into tblBook values (book_seq.nextVal, '언어의 아이들', '유노북스', '조지은', 494, 76, 0);
insert into tblBook values (book_seq.nextVal, '중국을 사랑한 남자', '갈무리', '사이먼 윈체스터 ', 478, 35, 0);
insert into tblBook values (book_seq.nextVal, '자연의 패턴', 'Mirae N 아이세움 :미래엔', '필립 볼 ', 472, 53, 0);
insert into tblBook values (book_seq.nextVal, '과학 원리', '새움', 'DK 편집위원회 ', 402, 98, 0);
insert into tblBook values (book_seq.nextVal, '무기 2판', '플랜비디자인', 'DK 편집위원회 ', 415, 81, 0);
insert into tblBook values (book_seq.nextVal, '송기원의 포스트 게놈 시대', '사파리 :이퍼블릭', '송기원', 471, 40, 0);
insert into tblBook values (book_seq.nextVal, '물속을 나는 새', '좋은책신사고:좋은책어린이', '이원영', 460, 22, 0);
insert into tblBook values (book_seq.nextVal, '오리진', '모과나무', '닐 디그래스 타이슨', 491, 19, 0);
insert into tblBook values (book_seq.nextVal, '코스믹 커넥션', '백문백답', '칼 세이건 ', 444, 80, 0);
insert into tblBook values (book_seq.nextVal, '세실의 전설', 'M&K:엠앤키즈', '브렌트 스타펠캄프 ', 459, 21, 0);
insert into tblBook values (book_seq.nextVal, '로봇 수업', '책과콩나무', '존 조던 ', 479, 15, 0);
insert into tblBook values (book_seq.nextVal, '탱크 북', '검은숲 :시공사', '데이비드 윌리 ', 463, 53, 0);
insert into tblBook values (book_seq.nextVal, '물리의 정석: 양자 역학 편', '교보문고', '레너드 서스킨드', 465, 66, 0);
insert into tblBook values (book_seq.nextVal, '블랙홀 옆에서', '더퀘스트 :길벗', '닐 디그래스 타이슨 ', 454, 06, 0);
insert into tblBook values (book_seq.nextVal, '돈의 원리', '까치', 'DK 편집위원회 ', 458, 20, 0);
insert into tblBook values (book_seq.nextVal, '음식 원리', '리더스북 :웅진씽크빅', 'DK 편집위원회 ', 485, 81, 0);
insert into tblBook values (book_seq.nextVal, '날마다 천체 물리', '채움과 사람들', '닐 디그래스 타이슨', 416, 90, 0);
insert into tblBook values (book_seq.nextVal, '클래식 파인만', '플랜비디자인', '리처드 파인만', 467, 06, 0);
insert into tblBook values (book_seq.nextVal, '생명의 이름', '자음과모음', '권오길', 468, 75, 0);
insert into tblBook values (book_seq.nextVal, '지구의 절반', '단비어린이:가치창조', '에드워드 윌슨  ', 409, 10, 0);
insert into tblBook values (book_seq.nextVal, '양자 정보학 강의', '좋은책어린이:좋은책신사고', '이해웅', 470, 87, 0);
insert into tblBook values (book_seq.nextVal, '과학은 그 책을 고전이라 한다', '주니어골든벨', '강양구', 446, 70, 0);
insert into tblBook values (book_seq.nextVal, '김상욱의 양자 공부', '에이콘출판', '김상욱', 436, 30, 0);
insert into tblBook values (book_seq.nextVal, '네이버후드 프로젝트', '위즈덤하우스 :위즈덤하우스 미디어그룹', '데이비드 슬론 윌슨 ', 481, 86, 0);
insert into tblBook values (book_seq.nextVal, '백년 목', '까치 :까치글방', '정선근', 481, 15, 0);
insert into tblBook values (book_seq.nextVal, '빅 히스토리', '북캠퍼스', '데이비드 크리스천 ', 468, 03, 0);
insert into tblBook values (book_seq.nextVal, '물리의 정석: 고전 역학 편', '터치아트', '레너드 서스킨드', 402, 57, 0);
insert into tblBook values (book_seq.nextVal, '인체 완전판(2판)', '센시오', '앨리스 로버츠 ', 497, 55, 0);
insert into tblBook values (book_seq.nextVal, '초유기체', '아울북 :북이십일 아울북', '베르트 횔도블러', 413, 06, 0);
insert into tblBook values (book_seq.nextVal, '이휘소 평전', '미메시스', '강주상', 424, 91, 0);
insert into tblBook values (book_seq.nextVal, '김명호의 과학 뉴스', '청어람아이:청어람미디어', '김명호', 425, 22, 0);
insert into tblBook values (book_seq.nextVal, '인체 원리', '모모', 'DK 편집위원회 ', 470, 33, 0);
insert into tblBook values (book_seq.nextVal, '비행기 대백과사전', '흐름출판', '필립 화이트먼 ', 419, 74, 0);
insert into tblBook values (book_seq.nextVal, '모든 사람을 위한 빅뱅 우주론 강의(증보판)', '경원북스', '이석영', 456, 99, 0);
insert into tblBook values (book_seq.nextVal, '나의 코스모스', 'Mirae N 아이세움 :미래엔', '홍승수', 491, 70, 0);
insert into tblBook values (book_seq.nextVal, '개미와 공작', '고래가숨쉬는도서관', '헬레나 크로닌 ', 454, 67, 0);
insert into tblBook values (book_seq.nextVal, '우리 과학 문화재의 한길에 서서', '아이노리', '전상운', 499, 66, 0);
insert into tblBook values (book_seq.nextVal, '혜성', 'Taste books:테이스트북스:문학동네', '칼 세이건', 477, 16, 0);
insert into tblBook values (book_seq.nextVal, '공룡의 나라 한반도', '수오서재', '허민', 412, 53, 0);
insert into tblBook values (book_seq.nextVal, '지구의 속삭임', '책밥', '칼 세이건', 495, 40, 0);
insert into tblBook values (book_seq.nextVal, '세상 모든 비밀을 푸는 수학', '교유당', '이창옥', 473, 90, 0);
insert into tblBook values (book_seq.nextVal, '우리는 지금도 야생을 산다', '꾸리에:꾸리에북스', '에드워드 윌슨  ', 450, 53, 0);
insert into tblBook values (book_seq.nextVal, '인간 존재의 의미', '가람어린이', '에드워드 윌슨  ', 452, 13, 0);
insert into tblBook values (book_seq.nextVal, '불멸의 원자', '책빛', '이강영', 446, 62, 0);
insert into tblBook values (book_seq.nextVal, '암흑 물질과 공룡', 'water bear press:워터베어프레스', '리사 랜들', 412, 51, 0);
insert into tblBook values (book_seq.nextVal, '조선의 비행기, 다시 하늘을 날다', '북뱅크', '이봉섭', 452, 55, 0);
insert into tblBook values (book_seq.nextVal, '본성이 답이다', '백문백답', '전중환', 493, 89, 0);
insert into tblBook values (book_seq.nextVal, '판다의 엄지', '갈무리', '스티븐 제이 굴드 ', 477, 49, 0);
insert into tblBook values (book_seq.nextVal, '새로운 두 과학', '어니스트북스 :어니스트펫', '갈릴레오 갈릴레이 ', 464, 67, 0);
insert into tblBook values (book_seq.nextVal, '대화', '리수', '갈릴레오 갈릴레이', 427, 61, 0);
insert into tblBook values (book_seq.nextVal, '수소 폭탄 만들기', '지학사 :북트리거', '리처드 로즈 ', 479, 00, 0);
insert into tblBook values (book_seq.nextVal, '기발한 과학책', '디 이니셔티브', '미첼 모피트', 406, 59, 0);
insert into tblBook values (book_seq.nextVal, '세계를 바꾼 17가지 방정식', '분홍고래', '이언 스튜어트  ', 436, 97, 0);
insert into tblBook values (book_seq.nextVal, '백년 허리', '지오북:Geobook', '정선근', 428, 98, 0);
insert into tblBook values (book_seq.nextVal, '엔진의 시대', '영진미디어', '폴 인그래시아 ', 447, 45, 0);
insert into tblBook values (book_seq.nextVal, '천국의 문을 두드리며', '책밥', '리사 랜들 ', 417, 57, 0);
insert into tblBook values (book_seq.nextVal, '김명호의 생물학 공방', '한겨례아이들 :한겨레출판', '김명호', 474, 02, 0);
insert into tblBook values (book_seq.nextVal, '모든 사람을 위한 지진 이야기', '21세기북스 :북이십일 21세기북스', '이기화', 412, 20, 0);
insert into tblBook values (book_seq.nextVal, '인류의 기원', '마음서재', '이상희', 477, 30, 0);
insert into tblBook values (book_seq.nextVal, '미로 속의 암소', 'CH북스', '이언 스튜어트  ', 464, 66, 0);
insert into tblBook values (book_seq.nextVal, '나는 자연에 투자한다', '북플라자', '마크 터섹', 463, 48, 0);
insert into tblBook values (book_seq.nextVal, '생명의 수학', '북하우스:북하우스 리퍼블리셔스', '이언 스튜어트  ', 496, 68, 0);
insert into tblBook values (book_seq.nextVal, '과학 수다 2', '아르띠잔', '이명현', 413, 80, 0);
insert into tblBook values (book_seq.nextVal, '과학 수다 1', '비글스쿨', '이명현', 413, 08, 0);
insert into tblBook values (book_seq.nextVal, '비행의 시대', '웅진지식하우스 :웅진씽크빅', '장조원', 409, 38, 0);
insert into tblBook values (book_seq.nextVal, '비숲', '샘터', '김산하', 446, 96, 0);
insert into tblBook values (book_seq.nextVal, '다윈과 함께', 'Haru:하루:터닝포인트', '홍성욱', 420, 63, 0);
insert into tblBook values (book_seq.nextVal, '유전자 전쟁의 현대사 산책', '랭기지플러스', '이병훈', 455, 43, 0);
insert into tblBook values (book_seq.nextVal, '빅뱅 스쿨 9', '썬더키즈 :썬더버드', '홍승우', 491, 72, 0);
insert into tblBook values (book_seq.nextVal, '별빛 방랑', '비채 :김영사', '황인준', 451, 86, 0);
insert into tblBook values (book_seq.nextVal, '수학의 파노라마', '현대지성', '클리퍼드 픽오버 ', 463, 24, 0);
insert into tblBook values (book_seq.nextVal, '왕의 한의학', '책비', '이상곤', 449, 48, 0);
insert into tblBook values (book_seq.nextVal, '희망의 씨앗', '동인랑', '제인 구달', 453, 47, 0);
insert into tblBook values (book_seq.nextVal, '책 대 책', 'Terra :테라', '고중숙', 486, 85, 0);
insert into tblBook values (book_seq.nextVal, '내일의 경제', '동북아역사재단', '마크 뷰캐넌  ', 474, 63, 0);
insert into tblBook values (book_seq.nextVal, '바벨탑의 힉스 사냥꾼', 'xbooks:엑스북스', '김동희', 401, 71, 0);
insert into tblBook values (book_seq.nextVal, '꿈틀꿈틀 곤충 왕국', '민음사', '한영식 ', 425, 27, 0);
insert into tblBook values (book_seq.nextVal, '우리 본성의 선한 천사', '거북이북스', '스티븐 핑커 ', 417, 08, 0);
insert into tblBook values (book_seq.nextVal, '중국의 과학문명', '스몰빅라이프 :스몰빅미디어', '야부우치 기요시 ', 484, 00, 0);
insert into tblBook values (book_seq.nextVal, '1.4킬로그램의 우주, 뇌', '철수와영희', '정재승', 474, 77, 0);
insert into tblBook values (book_seq.nextVal, '임신과 출산', '아카넷', '윤미진', 456, 93, 0);
insert into tblBook values (book_seq.nextVal, '초신성의 후예', '파람북', '이석영', 456, 25, 0);
insert into tblBook values (book_seq.nextVal, '오래된 연장통 증보판', '지브레인', '전중환', 464, 92, 0);
insert into tblBook values (book_seq.nextVal, '정체학', '투나미스', '니시나리 가쓰히로 ', 450, 35, 0);
insert into tblBook values (book_seq.nextVal, '낭비학', '홍익출판사', '니시나리 가쓰히로 ', 464, 03, 0);
insert into tblBook values (book_seq.nextVal, '가지', '비채 :김영사', '필립 볼 ', 454, 18, 0);
insert into tblBook values (book_seq.nextVal, '흐름', '씽크스마트', '필립 볼 ', 489, 97, 0);
insert into tblBook values (book_seq.nextVal, '모양', '홈앤에듀', '필립 볼 ', 415, 70, 0);
insert into tblBook values (book_seq.nextVal, '정신병을 만드는 사람들', '비채 :김영사', '앨런 프랜시스 ', 437, 76, 0);
insert into tblBook values (book_seq.nextVal, '과학의 민중사', '글항아리', '클리퍼드 코너', 442, 80, 0);
insert into tblBook values (book_seq.nextVal, '우리 혜성 이야기', '키즈엠:Kids-M', '안상현', 434, 31, 0);
insert into tblBook values (book_seq.nextVal, '미지에서 묻고 경계에서 답하다', 'Izi publishing:이지퍼블리싱', 'APCTP', 421, 06, 0);
insert into tblBook values (book_seq.nextVal, '빛의 공학', '타커스', '석현정', 446, 42, 0);
insert into tblBook values (book_seq.nextVal, '할리우드 사이언스', '미메시스', '김명진', 450, 34, 0);
insert into tblBook values (book_seq.nextVal, '지구의 정복자', '이야기가있는집', '에드워드 윌슨  ', 435, 09, 0);
insert into tblBook values (book_seq.nextVal, '신경 과학의 철학', '상상출판', '맥스웰 R. 베넷', 499, 76, 0);
insert into tblBook values (book_seq.nextVal, '공감 제로', '나남', '사이먼 배런코언(Simon Baron-Cohen) ', 425, 26, 0);
insert into tblBook values (book_seq.nextVal, '세계 문학 속 지구 환경 이야기 2', '휴머니스트 :휴머니스트 출판그룹', '이시 히로유키 ', 441, 73, 0);
insert into tblBook values (book_seq.nextVal, '세계 문학 속 지구 환경 이야기 1', '바이북스', '이시 히로유키 ', 464, 50, 0);
insert into tblBook values (book_seq.nextVal, '백인천 프로젝트 ', '소원나무', '정재승', 464, 50, 0);
insert into tblBook values (book_seq.nextVal, '예수와 다윈의 동행', '진선아이 :진선출판사', '신재식', 434, 07, 0);
insert into tblBook values (book_seq.nextVal, '보일러플레이트', '돌베개', '폴 기난', 462, 97, 0);
insert into tblBook values (book_seq.nextVal, '생명 교향곡', '한겨레아이들 :한겨례출판', '권오길', 481, 22, 0);
insert into tblBook values (book_seq.nextVal, '구글 신은 모든 것을 알고 있다', '더메이커', '정하웅', 481, 27, 0);
insert into tblBook values (book_seq.nextVal, '동아시아 과학의 차이', '하움출판사', '김영식 ', 406, 49, 0);
insert into tblBook values (book_seq.nextVal, '빅뱅 스쿨 8', '어니스트북스 :어니스트펫', '전상운 ', 465, 05, 0);
insert into tblBook values (book_seq.nextVal, '개미언덕', 'AK Trivia Special :에이케이 커뮤니케이션즈', '에드워드 윌슨  ', 489, 28, 0);
insert into tblBook values (book_seq.nextVal, '이것이 힉스다', '살림', '리사 랜들', 408, 22, 0);
insert into tblBook values (book_seq.nextVal, '카 북', 'IVP:한국기독학생회출판부', '자일스 채프먼', 432, 40, 0);
insert into tblBook values (book_seq.nextVal, '초협력자', '어바웃어북', '마틴 노왁', 446, 79, 0);
insert into tblBook values (book_seq.nextVal, '자연사', 'BM성안당 :성안당', '스미스소니언 협회 ', 427, 22, 0);
insert into tblBook values (book_seq.nextVal, '인간다움의 조건', '파라아카데미:파라북스', '스튜어트 월턴 ', 470, 70, 0);
insert into tblBook values (book_seq.nextVal, '인체 완전판', '아이쿱협동조합연구소', '앨리스 로버츠 ', 470, 83, 0);
insert into tblBook values (book_seq.nextVal, '물리학 클래식', '미디어숲 :다빈치하우스', '이종필', 439, 50, 0);
insert into tblBook values (book_seq.nextVal, '[사이언스클래식22] 다시 만들어진 신', 'Mons:몽스북', '스튜어트 앨런 카우프만 ', 432, 25, 0);
insert into tblBook values (book_seq.nextVal, '10의 제곱수', '웅진주니어 :웅진씽크빅', '필립 모리슨 ', 438, 20, 0);
insert into tblBook values (book_seq.nextVal, '해부학자', '에듀니티', '빌 헤이스 ', 435, 95, 0);
insert into tblBook values (book_seq.nextVal, '융합이란 무엇인가', '키위북스', '박상욱', 405, 79, 0);
insert into tblBook values (book_seq.nextVal, '과학을 성찰하다', '여유당출판사', '임경순', 482, 79, 0);
insert into tblBook values (book_seq.nextVal, '와인에 담긴 과학', '주니어김영사 :김영사', '강호정', 442, 53, 0);
insert into tblBook values (book_seq.nextVal, '다윈 지능', '초록개구리', '최재천', 416, 10, 0);
insert into tblBook values (book_seq.nextVal, '자연과 권력', '시대의창', '요아힘 라트카우 ', 492, 25, 0);
insert into tblBook values (book_seq.nextVal, '뫼비우스의 띠', '사이드웨이', '클리퍼드 픽오버 ', 441, 77, 0);
insert into tblBook values (book_seq.nextVal, '시민의 과학', 'Kids-M:키즈엠', '시민과학센터', 420, 13, 0);
insert into tblBook values (book_seq.nextVal, '지구를 부탁해', '샘터', '박동곤 ', 436, 32, 0);
insert into tblBook values (book_seq.nextVal, '우리 회의나 할까?', '꾸리에:꾸리에북스', '김민철', 487, 02, 0);
insert into tblBook values (book_seq.nextVal, '땅의 마음', '다락원', '윤홍기', 423, 99, 0);
insert into tblBook values (book_seq.nextVal, '화석이 말을 한다면', '고래가숨쉬는도서관', '김동희', 418, 49, 0);
insert into tblBook values (book_seq.nextVal, '요리 본능', '궁리', '리처드 랭엄 ', 440, 86, 0);
insert into tblBook values (book_seq.nextVal, '[사이언스클래식19]블랙홀 전쟁', '21세기북스 :북이십일 21세기북스', '레너드 서스킨드 ', 462, 85, 0);
insert into tblBook values (book_seq.nextVal, '낮은 한의학', 'Hama:하마출판사', '이상곤', 477, 00, 0);
insert into tblBook values (book_seq.nextVal, '동물원 아기들', '고래가숨쉬는도서관', '앤드루 블라이먼', 499, 12, 0);
insert into tblBook values (book_seq.nextVal, '빅뱅 스쿨 7', '메이트북스 :원앤원콘텐츠그룹', '전상운 ', 424, 88, 0);
insert into tblBook values (book_seq.nextVal, '아톰의 시대에서 코난의 시대로', '코끼리아저씨', '강양구', 499, 45, 0);
insert into tblBook values (book_seq.nextVal, '뇌과학 여행자', '책숲', '김종성', 425, 94, 0);
insert into tblBook values (book_seq.nextVal, '원자력 딜레마', '비즈니스북스', '김명자', 408, 58, 0);
insert into tblBook values (book_seq.nextVal, '사이언스 클래식 18 우주의 풍경', '담앤북스', '레너드 서스킨드 ', 460, 39, 0);
insert into tblBook values (book_seq.nextVal, '마음의 시계', '반비', '엘렌 랭어', 431, 94, 0);
insert into tblBook values (book_seq.nextVal, '과학 윤리 특강', '키즈엠:Kids-M', '엘렌 랭어', 447, 72, 0);
insert into tblBook values (book_seq.nextVal, '또 하나의 뇌 위장', '주니어김영사 :김영사', '송인성', 464, 14, 0);
insert into tblBook values (book_seq.nextVal, 'LHC, 현대물리학의 최전선', '가지', '이강영', 419, 28, 0);
insert into tblBook values (book_seq.nextVal, '웃음의 과학', 'YBM홀딩스:와이비엠홀딩스', '이윤석', 496, 99, 0);
insert into tblBook values (book_seq.nextVal, '눈이 즐거운 물리', '니들북:대원씨아이', '김상협', 466, 03, 0);
insert into tblBook values (book_seq.nextVal, '바이오필리아', '리버티', '에드워드 윌슨 ', 454, 64, 0);
insert into tblBook values (book_seq.nextVal, '희망의 자연', '진선아트북:진선출판사', '제인 구달 ', 440, 78, 0);
insert into tblBook values (book_seq.nextVal, '여자가 섹스를 하는 237가지 이유', '찰리북', '데이비드 버스', 466, 76, 0);
insert into tblBook values (book_seq.nextVal, '세상을 바꾼 독약 한 방울[2]', '노루궁뎅이', '존 엠슬리 ', 451, 47, 0);
insert into tblBook values (book_seq.nextVal, '세상을 바꾼 독약 한 방울[1]', '동북아역사재단', '존 엠슬리 ', 410, 94, 0);
insert into tblBook values (book_seq.nextVal, '사회적 원자', '성균관대학교 출판부', '마크 뷰캐넌  ', 421, 82, 0);
insert into tblBook values (book_seq.nextVal, '아메리칸 프로메테우스', '인플루엔셜', '카이 버드', 473, 66, 0);
insert into tblBook values (book_seq.nextVal, '오늘의 과학', '다산에듀 :다산북스', '서유헌', 471, 35, 0);
insert into tblBook values (book_seq.nextVal, '빅뱅 스쿨 6', '지식의숲', '전상운 ', 430, 24, 0);
insert into tblBook values (book_seq.nextVal, '과학적 경험의 다양성[사이언스 클래식16]', 'BM성안북스', '칼 세이건', 492, 99, 0);
insert into tblBook values (book_seq.nextVal, '백두산 대폭발의 비밀', '글ego', '소원주', 459, 41, 0);
insert into tblBook values (book_seq.nextVal, '어머니의 탄생[사이언스 클래식15]', 'Human & Books', '세라 블래퍼 허디 ', 420, 12, 0);
insert into tblBook values (book_seq.nextVal, '불확실한 세상', '사계절', '김재영', 448, 65, 0);
insert into tblBook values (book_seq.nextVal, '우리에게 과학이란 무엇인가', '한빛비즈', 'APCTP', 479, 94, 0);
insert into tblBook values (book_seq.nextVal, '사람을 구하는 집, 제중원', '키즈엠:Kids-M', '박형우', 465, 24, 0);
insert into tblBook values (book_seq.nextVal, '무기', '내인생의책', '로저 포드', 417, 80, 0);
insert into tblBook values (book_seq.nextVal, '단어와 규칙', '풀빛미디어', '스티븐 핑커 ', 450, 13, 0);
insert into tblBook values (book_seq.nextVal, '1마일 속의 우주', '미래지향', '쳇 레이모  ', 445, 14, 0);
insert into tblBook values (book_seq.nextVal, '빅뱅 스쿨 5', '타커스', '홍승우', 446, 42, 0);
insert into tblBook values (book_seq.nextVal, '21세기 다윈 혁명', '학고재', '강호정', 422, 66, 0);
insert into tblBook values (book_seq.nextVal, '우주의 기원', 'Human & Books', '존 배로 ', 499, 00, 0);
insert into tblBook values (book_seq.nextVal, '진화의 미스터리', '책읽는곰', '조지 윌리엄즈 ', 421, 03, 0);
insert into tblBook values (book_seq.nextVal, '닥터 골렘', '한겨레출판', '해리 콜린스', 429, 36, 0);
insert into tblBook values (book_seq.nextVal, '종교전쟁', '소미미디어:somy media', '신재식', 474, 72, 0);
insert into tblBook values (book_seq.nextVal, '갈릴레오', '자주보라', '마이클 화이트  ', 466, 53, 0);
insert into tblBook values (book_seq.nextVal, '하늘을 보는 눈', '미디어숲 :다빈치하우스', '고베르트 실링', 492, 22, 0);
insert into tblBook values (book_seq.nextVal, '초능력 동물원', '안전가옥', '김소희 ', 412, 99, 0);
insert into tblBook values (book_seq.nextVal, '겨우 존재하는 것들 2.0', 'Vitamin Book:비타민 북', '김제완', 482, 52, 0);
insert into tblBook values (book_seq.nextVal, '담장 속의 과학', '한국수필가협회 :코드미디어', '이재열', 432, 99, 0);
insert into tblBook values (book_seq.nextVal, '몽상의 물리학자 프리먼 다이슨, 20세기를 말하다', '부키', '프리먼 다이슨 ', 400, 65, 0);
insert into tblBook values (book_seq.nextVal, '빅뱅 스쿨 4', '시크릿하우스', '홍승우', 490, 19, 0);
insert into tblBook values (book_seq.nextVal, '다윈 이후', '문학사상', '스티븐 제이 굴드 ', 464, 67, 0);
insert into tblBook values (book_seq.nextVal, 'STRESS(스트레스)', '그레이트BOOKS:그레이트북스', '로버트 새폴스키 ', 497, 45, 0);
insert into tblBook values (book_seq.nextVal, '과학이 나를 부른다', '현암주니어 :현암사', '강신주', 438, 04, 0);
insert into tblBook values (book_seq.nextVal, '진화란 무엇인가', 'AK Trivia Special :에이케이 커뮤니케이션즈', '에른스트 마이어 ', 466, 78, 0);
insert into tblBook values (book_seq.nextVal, '밤의 물리학', '북멘토', '다케우치 가오루 ', 435, 70, 0);
insert into tblBook values (book_seq.nextVal, '빅뱅 스쿨 3', 'Humanist:휴머니스트 출판그룹', '홍승우', 420, 85, 0);
insert into tblBook values (book_seq.nextVal, '반딧불이 통신', '시공주니어 :시공사', '한영식  ', 448, 36, 0);
insert into tblBook values (book_seq.nextVal, '성도', '초록아이', '조상호', 496, 99, 0);
insert into tblBook values (book_seq.nextVal, '자오선 여행', '필로소픽', '쳇 레이모  ', 498, 56, 0);
insert into tblBook values (book_seq.nextVal, '잊혀진 조상의 그림자', '지학사 :북트리거', '앤 드루얀', 465, 90, 0);
insert into tblBook values (book_seq.nextVal, '한국의 전통생태학 2', '책읽는달', '이도원', 492, 95, 0);
insert into tblBook values (book_seq.nextVal, '타고난 반항아', '마티', '프랭크 설로웨이 ', 413, 21, 0);
insert into tblBook values (book_seq.nextVal, '나의 첫 여름', '제이펍', '존 뮤어 ', 422, 39, 0);
insert into tblBook values (book_seq.nextVal, '파인만!', '사파리 :이퍼블릭', '리처드 파인만 ', 471, 91, 0);
insert into tblBook values (book_seq.nextVal, '문더스트', '푸른숲주니어:푸른숲', '앤드루 스미스', 407, 53, 0);
insert into tblBook values (book_seq.nextVal, '숨겨진 우주', '유노라이프', '리사 랜들 ', 479, 45, 0);
insert into tblBook values (book_seq.nextVal, '빅뱅 스쿨 2', 'BM성안당:성안당', '홍승우', 467, 39, 0);
insert into tblBook values (book_seq.nextVal, '소로의 속삭임', '도림북스', '김욱동', 452, 87, 0);
insert into tblBook values (book_seq.nextVal, '빅뱅 스쿨 1', '구층책방:동아출판', '홍승우', 413, 56, 0);
insert into tblBook values (book_seq.nextVal, '보바리의 남자 오셀로의 여자', '달아실', '데이비드 바래시', 469, 16, 0);
insert into tblBook values (book_seq.nextVal, '공생자 행성', '내친구의서재', '안은실', 413, 88, 0);
insert into tblBook values (book_seq.nextVal, '최종 이론의 꿈', '디 이니셔티브', '스티븐 와인버그 ', 451, 26, 0);
insert into tblBook values (book_seq.nextVal, '생명의 편지', '지오북:Geobook', '에드워드 윌슨  ', 499, 38, 0);
insert into tblBook values (book_seq.nextVal, '양자 중력의 세 가지 길', '미호', '김낙우', 484, 93, 0);
insert into tblBook values (book_seq.nextVal, '욕망의 진화', '이마주', '데이비드 버스 ', 470, 42, 0);
insert into tblBook values (book_seq.nextVal, '수학나라 어글리빌 시장의 딜레마', '아모르문디', '이언 스튜어트 ', 442, 18, 0);
insert into tblBook values (book_seq.nextVal, '감정의 롤러코스터', '에듀니티', '클라우디아 해먼드  ', 452, 05, 0);
insert into tblBook values (book_seq.nextVal, '어떻게 부자가 될까?', '종문화사', '롤랜드 모건 ', 402, 73, 0);
insert into tblBook values (book_seq.nextVal, '어떻게 영원히 살까?', 'BM성안북스', '닉 아놀드  ', 421, 43, 0);
insert into tblBook values (book_seq.nextVal, '어떻게 양을 복제할까?', '북플라자', '헤이즐 리처드슨 ', 455, 28, 0);
insert into tblBook values (book_seq.nextVal, '어떻게 타임머신을 만들까?', '니들북:대원씨아이', '헤이즐 리처드슨 ', 460, 92, 0);
insert into tblBook values (book_seq.nextVal, '어떻게 달을 여행할까?', '터닝포인트', '헤이즐 리처드슨 ', 427, 16, 0);
insert into tblBook values (book_seq.nextVal, '어떻게 원자를 쪼갤까?', '시그마북스', '헤이즐 리처드슨 ', 405, 68, 0);
insert into tblBook values (book_seq.nextVal, '어떻게 로봇을 만들까?', '창비E :창비교육', '클리브 기포드 ', 496, 53, 0);
insert into tblBook values (book_seq.nextVal, '어떻게 영재가 될까?', '썬더키즈 :썬더버드', '조나단 핸콕 ', 414, 48, 0);
insert into tblBook values (book_seq.nextVal, '어떻게 화성을 개척할까?', '미행', '클리브 기포드 ', 401, 03, 0);
insert into tblBook values (book_seq.nextVal, '어떻게 인터넷을 잘할까?', '꿈터', '이안 루이스 ', 462, 50, 0);
insert into tblBook values (book_seq.nextVal, '어떻게 외계인을 만날까?', 'Odos:오도스', '클리브 기포드 ', 413, 52, 0);
insert into tblBook values (book_seq.nextVal, '어떻게 지구를 구할까?', '팜파스', '바바라 테일러 ', 495, 80, 0);
insert into tblBook values (book_seq.nextVal, '별난 고양이 보르가르의 엉뚱한 천문학 교실 2', '청년의사', '마이클 벤틀리 ', 462, 62, 0);
insert into tblBook values (book_seq.nextVal, '별난 고양이 보르가르의 엉뚱한 천문학 교실 1', '다산에듀 :다산북스', '마이클 벤틀리 ', 432, 96, 0);
insert into tblBook values (book_seq.nextVal, '알칼릴리 교수의 블랙홀 교실', '미술문화', '짐 알칼릴리 ', 479, 03, 0);
insert into tblBook values (book_seq.nextVal, '스피노자의 뇌', '팬덤북스', '안토니오 다마지오 ', 434, 28, 0);
insert into tblBook values (book_seq.nextVal, '수학의 확실성', '알파미디어', '모리스 클라인 ', 485, 38, 0);
insert into tblBook values (book_seq.nextVal, '별난 고양이 보르가르의 엉뚱한 수학 교실 4', '봄나무', '폴 포글리노 ', 450, 62, 0);
insert into tblBook values (book_seq.nextVal, '별난 고양이 보르가르의 엉뚱한 수학 교실 2', '시공주니어 :시공사', '마샤 러너', 402, 92, 0);
insert into tblBook values (book_seq.nextVal, '별난 고양이 보르가르의 엉뚱한 수학 교실 1', '북캠퍼스', '마샤 러너', 480, 24, 0);
insert into tblBook values (book_seq.nextVal, '별난 고양이 보르가르의 엉뚱한 수학 교실 3', '생각의길 :아름다운사람들', '폴 포글리노 ', 403, 94, 0);
insert into tblBook values (book_seq.nextVal, '과학적 발견의 패턴', '별숲', '노우드 러셀 핸슨 ', 428, 65, 0);
insert into tblBook values (book_seq.nextVal, '역사를 바꾼 17가지 화학이야기 2', '갈무리', '페니 르 쿠터 ', 440, 30, 0);
insert into tblBook values (book_seq.nextVal, '역사를 바꾼 17가지 화학이야기 1', '로그인 :이퍼블릭', '페니 르 쿠터 ', 448, 14, 0);
insert into tblBook values (book_seq.nextVal, '노화의 과학', '예문아카이브', '로버트 리클레프스', 474, 65, 0);
insert into tblBook values (book_seq.nextVal, '코스모스', '다산책방:다산북스', '칼 세이건 ', 483, 35, 0);
insert into tblBook values (book_seq.nextVal, '어떻게 지구의 크기를 쟀을까?', '춘명', '안나 파리시 ', 421, 80, 0);
insert into tblBook values (book_seq.nextVal, '어떻게 지동설을 밝혀냈을까?', '스몰빅라이프 :스몰빅미디어', '안나 파리시 ', 407, 91, 0);
insert into tblBook values (book_seq.nextVal, '어떻게 만유인력을 발견했을까?', '현대문학', '안나 파리시 ', 495, 04, 0);
insert into tblBook values (book_seq.nextVal, '어떻게 수의 비밀을 풀었을까?', '미다스북스', '안나 파리시 ', 485, 20, 0);
insert into tblBook values (book_seq.nextVal, '생각하는 기계', '타임북스', '대니얼 힐리스 ', 433, 37, 0);
insert into tblBook values (book_seq.nextVal, '과학해서 행복한 사람들', '키위북스', '안여림', 495, 08, 0);
insert into tblBook values (book_seq.nextVal, '지구', '잇콘', '더글러스 팔머 ', 418, 17, 0);
insert into tblBook values (book_seq.nextVal, '죽음의 향연', '한울 :한울엠플러스', '리처드 로즈 ', 488, 67, 0);
insert into tblBook values (book_seq.nextVal, '생각의 탄생', '모과나무', '윌리엄 캘빈 ', 484, 60, 0);
insert into tblBook values (book_seq.nextVal, '여섯 개의 수', '와이즈베리 :미래엔', '마틴 리즈 ', 444, 54, 0);
insert into tblBook values (book_seq.nextVal, '히포크라테스 선서', '꿈초:키즈엠', '반덕진', 455, 92, 0);
insert into tblBook values (book_seq.nextVal, '에덴의 용', '별숲', '칼 세이건 ', 425, 08, 0);
insert into tblBook values (book_seq.nextVal, '아주 특별한 동물 별 이야기', '책빛', '김소희', 442, 08, 0);
insert into tblBook values (book_seq.nextVal, '이웃집 살인마', '지식너머', '데이비드 버스 ', 410, 42, 0);
insert into tblBook values (book_seq.nextVal, '인간', '정신세계사', '로버트 윈스턴 ', 491, 02, 0);
insert into tblBook values (book_seq.nextVal, '의학의 역사', '영진미디어', '재컬린 더핀  ', 414, 23, 0);
insert into tblBook values (book_seq.nextVal, '과학 글쓰기 핸드북', '이야기가있는집', '기노시타 고레오 ', 429, 07, 0);
insert into tblBook values (book_seq.nextVal, '정원의 수도사', '생각하는책상', '로빈 헤니그 ', 457, 76, 0);
insert into tblBook values (book_seq.nextVal, '파스퇴르', '길벗', '르네 뒤보  ', 431, 91, 0);
insert into tblBook values (book_seq.nextVal, '과학 글쓰기', '강', '김성수', 499, 21, 0);
insert into tblBook values (book_seq.nextVal, '인간, 개를 만나다', '리드리드출판', '콘라트 로렌츠  ', 474, 12, 0);
insert into tblBook values (book_seq.nextVal, '희망의 밥상', '즐거운상상', '제인 구달', 425, 56, 0);
insert into tblBook values (book_seq.nextVal, '마음의 진화', '예미', '대니얼 데닛 ', 450, 61, 0);
insert into tblBook values (book_seq.nextVal, '실험실 지구', '유유', '스티븐 슈나이더 ', 447, 43, 0);
insert into tblBook values (book_seq.nextVal, '생명의 미래', '열매하나', '에드워드 윌슨  ', 449, 10, 0);
insert into tblBook values (book_seq.nextVal, '자연의 패턴', '즐거운상상', '이언 스튜어트  ', 436, 28, 0);
insert into tblBook values (book_seq.nextVal, '에덴의 강', '42mediacontent:42미디어콘텐츠', '리처드 도킨스 ', 427, 14, 0);
insert into tblBook values (book_seq.nextVal, '휴먼 브레인', '거북이북스', '수전 그린필드 ', 471, 99, 0);
insert into tblBook values (book_seq.nextVal, '개에 대하여', '동양북스', '스티븐 부디안스키 ', 469, 12, 0);
insert into tblBook values (book_seq.nextVal, '고양이에 대하여', '알키 :시공사', '스티븐 부디안스키 ', 472, 30, 0);
insert into tblBook values (book_seq.nextVal, '제인 구달', '북트리거 :지학사', '제인 구달 ', 499, 15, 0);
insert into tblBook values (book_seq.nextVal, '원소의 왕국', '책속물고기', '피터 앳킨스  ', 467, 19, 0);
insert into tblBook values (book_seq.nextVal, '세포의 반란', '이담 Books :한국학술정보', '로버트 와인버그 ', 483, 23, 0);
insert into tblBook values (book_seq.nextVal, '인류의 기원', '교양인', '리차드 리키  ', 463, 36, 0);
insert into tblBook values (book_seq.nextVal, '섹스의 진화', '한울 :한울엠플러스', '제러드 다이아몬드 ', 495, 35, 0);
insert into tblBook values (book_seq.nextVal, '마지막 3분', '타커스', '폴 데이비스 ', 417, 00, 0);
insert into tblBook values (book_seq.nextVal, '나는 왜 너를 미워하는가?', '봄나무', '러시 W. 도지어 주니어  ', 487, 28, 0);
insert into tblBook values (book_seq.nextVal, '통섭', '북카라반', '에드워드 윌슨  ', 467, 81, 0);
insert into tblBook values (book_seq.nextVal, '춤추는 뇌', '가지', '김종성', 481, 57, 0);
insert into tblBook values (book_seq.nextVal, '새', '웅진지식하우스:웅진씽크빅', '유범주', 464, 54, 0);
insert into tblBook values (book_seq.nextVal, '어쩌면 사실일지도 모르는 9가지 크레이지 아이디어', 'Booksgo:북스고', '로버트 에를리히 ', 488, 05, 0);
insert into tblBook values (book_seq.nextVal, '코스모스', '봄볕', '칼 세이건 ', 452, 04, 0);
insert into tblBook values (book_seq.nextVal, '우리는 어떻게 과학자가 되었는가?', '프런티어 :한국경제신문 한경BP', '존 브록만 ', 487, 88, 0);
insert into tblBook values (book_seq.nextVal, '아름다운 밤하늘', '책읽는곰', '쳇 레이모  ', 494, 24, 0);
insert into tblBook values (book_seq.nextVal, '현대 의학, 그 위대한 도전의 역사', '창비E :창비교육', '예병일', 415, 09, 0);
insert into tblBook values (book_seq.nextVal, '구름을 사랑한 과학자', '시공주니어', '리처드 험블린  ', 457, 74, 0);
insert into tblBook values (book_seq.nextVal, '한국의 전통생태학', '유나', '이도원', 400, 34, 0);
insert into tblBook values (book_seq.nextVal, '눈먼 시계공', 'Andromedian :안드로메디언 :로크미디어', '리처드 도킨스 ', 411, 68, 0);
insert into tblBook values (book_seq.nextVal, '나는 물리학을 가지고 놀았다', '프시케의숲', '존 그리빈', 435, 25, 0);
insert into tblBook values (book_seq.nextVal, '남이야 뭐라 하건!', '생각의길 :아름다운사람들', '리처드 파인만 ', 472, 15, 0);
insert into tblBook values (book_seq.nextVal, '이공계 살리기', '이담Books:한국학술정보', '마이니치신문 과학환경부 ', 498, 02, 0);
insert into tblBook values (book_seq.nextVal, '흙에서 흙으로', '휴먼에듀 :휴먼어린이', '이도원', 428, 26, 0);
insert into tblBook values (book_seq.nextVal, '흐르는 강물 따라', '봄의정원', '이도원', 457, 62, 0);
insert into tblBook values (book_seq.nextVal, '빈 서판', '뭉치:동아엠앤비', '스티븐 핑커 ', 485, 87, 0);
insert into tblBook values (book_seq.nextVal, '남극 탐험의 꿈', '신정', '장순근', 425, 58, 0);
insert into tblBook values (book_seq.nextVal, '딱정벌레 왕국의 여행자', '책빛', '한영식  ', 461, 98, 0);
insert into tblBook values (book_seq.nextVal, '독감', '라이팅하우스', '지나 콜라타 ', 439, 11, 0);
insert into tblBook values (book_seq.nextVal, '레오나르도 다빈치 최초의 과학자', '생각하는책상', '마이클 화이트  ', 400, 41, 0);
insert into tblBook values (book_seq.nextVal, '얼굴', '소와다리', '대니얼 맥닐 ', 414, 68, 0);
insert into tblBook values (book_seq.nextVal, '도덕적 동물', '연담L', '로버트 라이트 ', 485, 53, 0);
insert into tblBook values (book_seq.nextVal, '태교혁명', '꾸리에:꾸리에북스', '피터 너대니얼스', 453, 55, 0);
insert into tblBook values (book_seq.nextVal, '알면 약, 모르면 병', '쓰다', '두재균', 470, 91, 0);
insert into tblBook values (book_seq.nextVal, '나는 외과 의사다', '하빌리스:대원씨아이', '강구정 ', 478, 14, 0);
insert into tblBook values (book_seq.nextVal, '나는 꽃과 나비를 그린다', '시공주니어 :시공사', '나카노 교코 ', 411, 05, 0);
insert into tblBook values (book_seq.nextVal, '세계를 바꾼 지도', '한길사', '사이먼 윈체스터 ', 496, 52, 0);
insert into tblBook values (book_seq.nextVal, '원자 폭탄 만들기 1', '청년의사', '리처드 로즈 ', 496, 32, 0);
insert into tblBook values (book_seq.nextVal, '원자 폭탄 만들기 2', '한겨레출판', '리처드 로즈 ', 436, 06, 0);
insert into tblBook values (book_seq.nextVal, '만화 중국 과학 이야기', '고요한숨 :리디', '타오룽 ', 413, 66, 0);
insert into tblBook values (book_seq.nextVal, '우아한 노년', '예문아카이브', '데이비드 스노든  ', 496, 19, 0);
insert into tblBook values (book_seq.nextVal, '사이언스 북', '까치 :까치글방', '나이젤 헤이 ', 414, 97, 0);
insert into tblBook values (book_seq.nextVal, '몸의 지혜', '여유당출판사', '셔윈 널랜드 ', 425, 94, 0);
insert into tblBook values (book_seq.nextVal, '생각하는 수학', '웅진주니어:웅진씽크빅', '야노 겐타로  ', 468, 52, 0);
insert into tblBook values (book_seq.nextVal, '물리학이란 무엇인가', '코드미디어 :한국수필가협회 출판부', '도모나가 신이치로 ', 433, 25, 0);
insert into tblBook values (book_seq.nextVal, '중국 의학은 어떻게 시작되었는가', '미래지향', '야마다 게이지 ', 443, 65, 0);
insert into tblBook values (book_seq.nextVal, '상상은 미래를 부른다', '제이펍', '최성우', 434, 92, 0);
insert into tblBook values (book_seq.nextVal, '0의 발견', '미호', '요시다 요이치   ', 426, 65, 0);
insert into tblBook values (book_seq.nextVal, '미생물의 힘', '이마주', '버나드 딕슨  ', 451, 75, 0);
insert into tblBook values (book_seq.nextVal, '혼돈의 가장자리', '골든어페어', '스튜어트 카우프만  ', 473, 05, 0);
insert into tblBook values (book_seq.nextVal, '로봇의 시대', '마리書舍', '도지마 와코  ', 442, 98, 0);
insert into tblBook values (book_seq.nextVal, '진화의 패턴', 'Kids-M:키즈엠', '로저 르윈 ', 427, 78, 0);
insert into tblBook values (book_seq.nextVal, '어떻게 부자가 될까?', '살림어린이:살림출판사', '롤랜드 모건 ', 499, 01, 0);
insert into tblBook values (book_seq.nextVal, '어떻게 영원히 살까?', 'Editus:에디투스', '닉 아놀드  ', 410, 33, 0);
insert into tblBook values (book_seq.nextVal, '어떻게 인터넷을 잘할까?', '초록개구리', '이안 루이스 ', 472, 14, 0);
insert into tblBook values (book_seq.nextVal, '어떻게 지구를 구할까?', '느린걸음', '바바라 테일러 ', 457, 80, 0);
insert into tblBook values (book_seq.nextVal, '어떻게 외계인을 만날까?', 'Haru:하루:터닝포인트', '클리브 기포드 ', 404, 81, 0);
insert into tblBook values (book_seq.nextVal, '풀하우스', 'Editus:에디투스', '스티븐 제이 굴드 ', 423, 32, 0);
insert into tblBook values (book_seq.nextVal, '창백한 푸른 점', '중앙books :중앙일보플러스', '칼 세이건 ', 428, 27, 0);
insert into tblBook values (book_seq.nextVal, '에필로그', '봄이아트북스', '칼 세이건 ', 424, 53, 0);
insert into tblBook values (book_seq.nextVal, '콘택트 1', '세종', '칼 세이건 ', 453, 81, 0);
insert into tblBook values (book_seq.nextVal, '콘택트 2', 'Humanist :휴머니스트 출판그룹', '칼 세이건 ', 449, 79, 0);
insert into tblBook values (book_seq.nextVal, '인간의 그늘에서', '고래뱃속', '제인 구달 ', 446, 03, 0);
insert into tblBook values (book_seq.nextVal, '숨겨진 질서', '마주별', '존 홀런드 ', 471, 67, 0);
insert into tblBook values (book_seq.nextVal, '천재성의 비밀', '아카넷', '아서 밀러 ', 419, 85, 0);
insert into tblBook values (book_seq.nextVal, '카오스와 불교', '빨간콩', '김용운', 487, 36, 0);
insert into tblBook values (book_seq.nextVal, '이타적 유전자', '인간사랑', '매트 리들리 ', 447, 39, 0);
insert into tblBook values (book_seq.nextVal, '전염병의 문화사', '민음사', '아노 카렌 ', 491, 89, 0);
insert into tblBook values (book_seq.nextVal, '프린키피아의 천재', '리수', '리처드 웨스트폴  ', 460, 90, 0);
insert into tblBook values (book_seq.nextVal, '네번째 불연속', 'Hu:ine :한국외국어대학교 지식출판콘텐츠원', '브루스 매즐리시  ', 457, 61, 0);
insert into tblBook values (book_seq.nextVal, '사랑을 위한 과학', '청어람아이:청어람미디어', '토머스 루이스 ', 436, 46, 0);
insert into tblBook values (book_seq.nextVal, '현대 의학의 위기', '현북스', '멜빈 코너 ', 432, 52, 0);
insert into tblBook values (book_seq.nextVal, '생태학', '북플라자', '유진 오덤  ', 419, 37, 0);
insert into tblBook values (book_seq.nextVal, '생태학', '미래지향', '유진 오덤  ', 441, 99, 0);
insert into tblBook values (book_seq.nextVal, '아이도루', '21세기북스 :북이십일 21세기북스', '윌리엄 깁슨 ', 404, 31, 0);
insert into tblBook values (book_seq.nextVal, '생명의 파노라마', '복복서가', '말론 호아글랜드', 465, 78, 0);
insert into tblBook values (book_seq.nextVal, '두 문화', '어문학사', 'C. P. 스노우 ', 429, 15, 0);
insert into tblBook values (book_seq.nextVal, '화학의 시대', '청어람아이:청어람미디어', '필립 볼 ', 429, 55, 0);
insert into tblBook values (book_seq.nextVal, '이런, 이게 바로 나야! 2', '파란정원:책먹는아이', '더글러스 호프스태터', 420, 11, 0);
insert into tblBook values (book_seq.nextVal, '이런, 이게 바로 나야! 1', '피플앤북스', '더글러스 호프스태터', 484, 45, 0);
insert into tblBook values (book_seq.nextVal, '과학의 파우스트', '아이노리', '에른스트 페터 피셔 ', 464, 08, 0);
insert into tblBook values (book_seq.nextVal, '인간 본성에 대하여', '동북아역사재단', '에드워드 윌슨  ', 456, 18, 0);
insert into tblBook values (book_seq.nextVal, '어떻게 로봇을 만들까?', 'Izi publishing:이지퍼블리싱', '클리브 기포드 ', 411, 77, 0);
insert into tblBook values (book_seq.nextVal, '어떻게 영재가 될까?', '고래가숨쉬는도서관', '조나단 핸콕 ', 456, 82, 0);
insert into tblBook values (book_seq.nextVal, '어떻게 화성을 개척할까?', '라이스메이커', '클리브 기포드 ', 468, 46, 0);
insert into tblBook values (book_seq.nextVal, '자연사박물관과 생물다양성', '세나북스', '이병훈', 491, 86, 0);
insert into tblBook values (book_seq.nextVal, '소설로 읽는 주니어 수학 1', '휴머니스트 :휴머니스트 출판그룹', '더그 맥뮬런 주니어 ', 402, 99, 0);
insert into tblBook values (book_seq.nextVal, '화학의 변명 2', '내친구의서재', '존 엠슬리 ', 443, 97, 0);
insert into tblBook values (book_seq.nextVal, '화학의 변명 1', 'Hada:하다', '존 엠슬리 ', 407, 70, 0);
insert into tblBook values (book_seq.nextVal, '화학의 변명 3', '생각하는책상', '존 엠슬리 ', 499, 69, 0);
insert into tblBook values (book_seq.nextVal, '수학 학습 심리학', '두레아이들', '리처드 스켐프  ', 451, 55, 0);
insert into tblBook values (book_seq.nextVal, '한국의 귀화식물', '생각비행', '김준민', 445, 54, 0);
insert into tblBook values (book_seq.nextVal, '솔로몬의 반지', '동녘사이언스', '콘라트 로렌츠  ', 458, 93, 0);
insert into tblBook values (book_seq.nextVal, '한국 과학사', '타보름교육', '전상운', 411, 84, 0);
insert into tblBook values (book_seq.nextVal, '파인만 씨, 농담도 잘하시네! 2', '마리書舍', '리처드 파인만 ', 477, 75, 0);
insert into tblBook values (book_seq.nextVal, '파인만 씨, 농담도 잘하시네! 1', '살림', '리처드 파인만 ', 417, 03, 0);
insert into tblBook values (book_seq.nextVal, 'CD-ROM과 함께 가는 태양계 여행', '지상사:청홍', '곽영직', 472, 32, 0);
insert into tblBook values (book_seq.nextVal, '보전 생물학', 'Taste books:테이스트북스:문학동네', '김진수', 404, 25, 0);
insert into tblBook values (book_seq.nextVal, '수학이 나를 불렀다', '지학사아르볼:지학사', '로버트 카니겔  ', 406, 56, 0);
insert into tblBook values (book_seq.nextVal, '물리학 환상여행', '키출판사', '로버트 길모어 ', 418, 58, 0);
insert into tblBook values (book_seq.nextVal, '21세기 과학의 쟁점', '어니스트북스 :어니스트펫', '임경순', 466, 01, 0);
insert into tblBook values (book_seq.nextVal, '어떻게 달을 여행할까?', '난다:문학동네', '헤이즐 리처드슨 ', 479, 16, 0);
insert into tblBook values (book_seq.nextVal, '어떻게 양을 복제할까?', '파란자전거', '헤이즐 리처드슨 ', 475, 25, 0);
insert into tblBook values (book_seq.nextVal, '어떻게 원자를 쪼갤까?', '자주보라', '헤이즐 리처드슨 ', 438, 59, 0);
insert into tblBook values (book_seq.nextVal, '어떻게 타임머신을 만들까?', '청어람아이:청어람미디어', '헤이즐 리처드슨 ', 426, 12, 0);
insert into tblBook values (book_seq.nextVal, '기후 변동', '베틀북', '토마스 그레델', 400, 63, 0);
insert into tblBook values (book_seq.nextVal, '인간은 왜 병에 걸리는가', '한빛미디어', '랜덜프 네스', 438, 51, 0);
insert into tblBook values (book_seq.nextVal, '과학사 X파일', '박영story :피와이메이트', '최성우', 477, 52, 0);
insert into tblBook values (book_seq.nextVal, '인공지능 이야기', '한빛라이프', '존 L. 캐스티  ', 434, 47, 0);
insert into tblBook values (book_seq.nextVal, '제인구달', '잇츠북', '제인 구달 ', 400, 84, 0);
insert into tblBook values (book_seq.nextVal, '오승은의 수능노트(국사,윤리)', '바이북스', '오승은 ', 461, 59, 0);
insert into tblBook values (book_seq.nextVal, '오승은의 수능노트(일반사회.한국지리)', '리수', '오승은 ', 424, 38, 0);
insert into tblBook values (book_seq.nextVal, '오승은의 수능노트(화학.생물)', '미래의창', '오승은 ', 421, 31, 0);
insert into tblBook values (book_seq.nextVal, '오승은의 수능노트(물리.지구과학)', 'Haru:하루:터닝포인트', '오승은 ', 418, 78, 0);
insert into tblBook values (book_seq.nextVal, '오승은의 수능노트(수학1)', '라이카미', '오승은 ', 435, 34, 0);
insert into tblBook values (book_seq.nextVal, '오승은의 수능노트(공통수학)', '위즈덤하우스:위즈덤하우스 미디어그룹', '오승은 ', 471, 06, 0);
insert into tblBook values (book_seq.nextVal, '오승은의 수능노트(수학2)', '피그마리온 :Easy&books', '오승은 ', 434, 38, 0);
insert into tblBook values (book_seq.nextVal, '사회생물학 논쟁', '로그인:이퍼블릭', '프란츠 M. 부케티츠  ', 402, 51, 0);
insert into tblBook values (book_seq.nextVal, '개미제국의 발견', '책밥', '최재천', 497, 12, 0);
insert into tblBook values (book_seq.nextVal, '현대 수학의 여행자', '소원나무', '이바스 피터슨 ', 454, 44, 0);
insert into tblBook values (book_seq.nextVal, 'CD-ROM과 함께 가는 별자리 여행', '별숲', '곽영직', 480, 58, 0);
insert into tblBook values (book_seq.nextVal, '미래는 어떻게 존재하는가', '철수와영희', '이인식', 461, 15, 0);
insert into tblBook values (book_seq.nextVal, '홈페이지 제대로 배우기', '문학동네', '송인식', 497, 11, 0);
insert into tblBook values (book_seq.nextVal, '놀라운 뇌의 세계', '피그마리온 :Easy&books', 'R.오른스타인', 407, 29, 0);
insert into tblBook values (book_seq.nextVal, '윈도우95 포켓 가이드', '유노라이프', 'MARAN GRAPHICS INC.  ', 425, 37, 0);
insert into tblBook values (book_seq.nextVal, '포토샵 아트 갤러리', '라이스메이커', '이경훈', 438, 95, 0);
insert into tblBook values (book_seq.nextVal, '마이클 조던이 공중에 오래 떠 있는 까닭은', '리리 퍼블리셔', '수잔 데이비스', 465, 12, 0);
insert into tblBook values (book_seq.nextVal, '고대 문명의 환경사', '부크럼', '도날드 휴즈 ', 461, 23, 0);
insert into tblBook values (book_seq.nextVal, '포토샵 4.0 제대로 배우기', '책세상', '이현상', 482, 66, 0);
insert into tblBook values (book_seq.nextVal, '진화론 논쟁', '타임북스', '에른스트 마이어 ', 455, 54, 0);
insert into tblBook values (book_seq.nextVal, '악마 같은 남성', 'Being:비잉:로크미디어', '리처드 랭햄', 472, 29, 0);
insert into tblBook values (book_seq.nextVal, '15분의 기적', '알키 :시공사', '김종철', 461, 30, 0);
insert into tblBook values (book_seq.nextVal, '컴퓨터 게임 테마파크', '책들의정원', '박철 ', 494, 99, 0);
insert into tblBook values (book_seq.nextVal, '인터넷 익스플로러 4.0 제대로 활용하기', '한겨레아이들 :한겨레출판', '송기범 ', 403, 77, 0);
insert into tblBook values (book_seq.nextVal, '비주얼베이직 5.0 제대로 배우기', '지학사아르볼 :지학사', '김효한', 465, 27, 0);
insert into tblBook values (book_seq.nextVal, '한글파워포인트 97 제대로 활용하기', '김영사', '이중훈', 412, 41, 0);
insert into tblBook values (book_seq.nextVal, '나의 홈페이지 만들기', '달아실', '이정헌', 470, 41, 0);
insert into tblBook values (book_seq.nextVal, '괴델의 삶', '자주보라', '하오 왕 ', 430, 88, 0);
insert into tblBook values (book_seq.nextVal, '피타고라스의 바지', '어바웃어북', '마거릿 버트하임 ', 411, 04, 0);
insert into tblBook values (book_seq.nextVal, '한글 워드 97 제대로 활용하기', '느린걸음', '이재호', 447, 17, 0);
insert into tblBook values (book_seq.nextVal, '자바 클래스 백과사전', '동인랑', '이재우', 494, 08, 0);
insert into tblBook values (book_seq.nextVal, '100년만에 다시 찾는 아인슈타인', '파란자전거', '임경순', 470, 81, 0);
insert into tblBook values (book_seq.nextVal, 'STS 무엇인가', '21세기북스:북이십일 21세기북스', '로버트 예거 ', 418, 63, 0);
insert into tblBook values (book_seq.nextVal, '비주얼 C++ 제대로 활용하기', '통나무', '이정규', 458, 95, 0);
insert into tblBook values (book_seq.nextVal, '한글오피스 97 제대로 활용하기', '한빛라이프', '정인숙', 478, 43, 0);
insert into tblBook values (book_seq.nextVal, '위장에 또하나의 뇌가있다', '예문사', '송인성', 419, 17, 0);
insert into tblBook values (book_seq.nextVal, '무한 그리고 그 너머', '책비', '엘리 마오 ', 469, 99, 0);
insert into tblBook values (book_seq.nextVal, '넷스케이프 커뮤니케이터 4.0 제대로 활용하기', '이봄', '이경재', 404, 30, 0);
insert into tblBook values (book_seq.nextVal, '상대성 이론의 참뜻', '두란노', '버트런드 러셀 ', 459, 03, 0);
insert into tblBook values (book_seq.nextVal, '더 다양한 인터넷 정보검색 비법', '문예출판사', '김종영', 434, 53, 0);
insert into tblBook values (book_seq.nextVal, '슈뢰딩거의 삶', '책비', '월터 캡스 ', 474, 87, 0);
insert into tblBook values (book_seq.nextVal, '보이지 않는 권력자', '벤트리', '이재열', 444, 88, 0);
insert into tblBook values (book_seq.nextVal, '확실성의 종말', '코난북스', '일리야 프리고진 ', 446, 79, 0);
insert into tblBook values (book_seq.nextVal, 'HTML JAVASCRIPT CGI 레퍼런스', '학고재', '황석호', 431, 63, 0);
insert into tblBook values (book_seq.nextVal, '마인드 머신', '두레아이들', '콜린 블레이크모어 ', 460, 15, 0);
insert into tblBook values (book_seq.nextVal, '미스터 파인만', '난다:문학동네', '리처드 파인만 ', 451, 69, 0);
insert into tblBook values (book_seq.nextVal, '도둑 맞은 미래', '한국수필가협회 :코드미디어', '테오 콜본', 412, 95, 0);
insert into tblBook values (book_seq.nextVal, '인터넷 제대로 배우기', '썬더키즈 :썬더버드', '이향선', 465, 48, 0);
insert into tblBook values (book_seq.nextVal, '물리학이 즐겁다', '문학사상', '곽영직', 461, 89, 0);
insert into tblBook values (book_seq.nextVal, '자연주의자', '책세상', '에드워드 윌슨 ', 410, 06, 0);
insert into tblBook values (book_seq.nextVal, '어느 수학자의 변명', '미호', '고드프레이 해럴드 하디  ', 400, 58, 0);
insert into tblBook values (book_seq.nextVal, '인간 게놈 프로젝트', '이비락 :이비컴', '로버트 쿡디간 ', 408, 95, 0);
insert into tblBook values (book_seq.nextVal, '과학철학이란 무엇인가', '팜파스', '박이문', 498, 23, 0);
insert into tblBook values (book_seq.nextVal, '겨우 존재하는 것들', 'BM성안당', '김제완', 498, 10, 0);
insert into tblBook values (book_seq.nextVal, '파스타 마스터 클래스', 'Editus:에디투스', '백지혜 ', 351, 01, 0);
insert into tblBook values (book_seq.nextVal, '그리너리 푸드 : 오늘도 초록', '에듀니티', '한은형', 598, 16, 0);
insert into tblBook values (book_seq.nextVal, '백성귀족 6 특장판', 'Haru:하루:터닝포인트', '아라카와 히로무 ', 933, 52, 0);
insert into tblBook values (book_seq.nextVal, '백성귀족 6', '내친구의서재', '아라카와 히로무 ', 902, 95, 0);
insert into tblBook values (book_seq.nextVal, '운명의 그림', '복복서가', '나카노 교코 ', 659, 73, 0);
insert into tblBook values (book_seq.nextVal, '해장 음식 : 나라 잃은 백성처럼 마신 다음 날에는', '행성B:행성비', '미깡', 773, 45, 0);
insert into tblBook values (book_seq.nextVal, '조식 : 아침을 먹다가 생각한 것들', '쌤앤파커스', '이다혜', 267, 20, 0);
insert into tblBook values (book_seq.nextVal, '소금, 지방, 산, 열', '한국소설가협회', '사민 노스랏', 552, 45, 0);
insert into tblBook values (book_seq.nextVal, '케이크CAKES', '글ego', '사카타 아키코 ', 844, 14, 0);
insert into tblBook values (book_seq.nextVal, '신新 무서운 그림', '현대문학', '나카노 교코 ', 018, 40, 0);
insert into tblBook values (book_seq.nextVal, '아이고 3', 'Jpub:제이펍', '김우준 ', 768, 21, 0);
insert into tblBook values (book_seq.nextVal, '아이고 2', '느린걸음', '김우준 ', 819, 06, 0);
insert into tblBook values (book_seq.nextVal, '무엇을 어떻게 요리할까', '피어오름', '제인 혼비 ', 714, 63, 0);
insert into tblBook values (book_seq.nextVal, '타임 인 조선 한양 편 하', '예문아카이브', '이윤창 ', 839, 66, 0);
insert into tblBook values (book_seq.nextVal, '타임 인 조선 한양 편 상', '더 디퍼런스', '이윤창 ', 004, 15, 0);
insert into tblBook values (book_seq.nextVal, '백성귀족 5', '개암나무', '아라카와 히로무 ', 832, 93, 0);
insert into tblBook values (book_seq.nextVal, '모험 에레키테 섬 2', '시공주니어', '츠루타 겐지 ', 923, 98, 0);
insert into tblBook values (book_seq.nextVal, '패밀리 밀  ', '사람in', '페란 아드리아 ', 739, 62, 0);
insert into tblBook values (book_seq.nextVal, '탁탁탁 지글지글 짠!', '책빛', '파이돈 프레스 ', 721, 53, 0);
insert into tblBook values (book_seq.nextVal, '아이와 함께하는 실버 스푼', '시공주니어 :시공사', '어맨다 그랜트 ', 357, 15, 0);
insert into tblBook values (book_seq.nextVal, '삼별초 1', '허밍버드 :백도씨', '형민우 ', 778, 24, 0);
insert into tblBook values (book_seq.nextVal, '얼굴', '푸른숲', '연상호 ', 264, 41, 0);
insert into tblBook values (book_seq.nextVal, '움비처럼', '책밥', '권혁주 ', 128, 53, 0);
insert into tblBook values (book_seq.nextVal, '실버 스푼', '웅진주니어 :웅진씽크빅', '파이돈 프레스 ', 488, 34, 0);
insert into tblBook values (book_seq.nextVal, '타임 인 조선 타임 리프 편 하', '사이드웨이', '이윤창 ', 019, 69, 0);
insert into tblBook values (book_seq.nextVal, '타임 인 조선 타임 리프 편 상', '다산어린이 :스튜디오다산', '이윤창 ', 386, 01, 0);
insert into tblBook values (book_seq.nextVal, '매일 15분 나만의 그림 한 끼', 'Cypress:싸이프레스', '대니 그레고리   ', 477, 37, 0);
insert into tblBook values (book_seq.nextVal, '인디언의 속삭임', '더퀘스트 :길벗', '김욱동', 977, 44, 0);
insert into tblBook values (book_seq.nextVal, '1900년 이후의 미술사 3판', '봄봄', '할 포스터', 085, 31, 0);
insert into tblBook values (book_seq.nextVal, '백성귀족 4', '미다스북스', '아라카와 히로무 ', 852, 00, 0);
insert into tblBook values (book_seq.nextVal, '설국열차 종착역', '노드미디어', '올리비에 보케', 748, 28, 0);
insert into tblBook values (book_seq.nextVal, '(뉴 52) 배트맨 6: 야간 순찰', '홍익출판사', '스콧 스나이더 ', 636, 02, 0);
insert into tblBook values (book_seq.nextVal, '스즈키 선생님 11', '수오서재', '다케토미 겐지 ', 196, 90, 0);
insert into tblBook values (book_seq.nextVal, '스즈키 선생님 10', '스몰빅라이프 :스몰빅미디어', '다케토미 겐지 ', 655, 48, 0);
insert into tblBook values (book_seq.nextVal, '스즈키 선생님 9', '민음사', '다케토미 겐지 ', 839, 24, 0);
insert into tblBook values (book_seq.nextVal, '예술가의 뒷모습', '고래가숨쉬는도서관', '세라 손튼 ', 708, 42, 0);
insert into tblBook values (book_seq.nextVal, '스즈키 선생님 5', '라이카미', '다케토미 겐지 ', 155, 52, 0);
insert into tblBook values (book_seq.nextVal, '스즈키 선생님 6', '파란자전거', '다케토미 겐지 ', 936, 27, 0);
insert into tblBook values (book_seq.nextVal, '스즈키 선생님 7', 'SoulHouse:소울하우스:아이씨티컴퍼니', '다케토미 겐지 ', 778, 23, 0);
insert into tblBook values (book_seq.nextVal, '스즈키 선생님 8', '한빛미디어', '다케토미 겐지 ', 109, 51, 0);
insert into tblBook values (book_seq.nextVal, '(뉴 52) 배트맨 5: 제로 이어 - 어둠의 도시', '어니스트북스 :어니스트펫', '스콧 스나이더 ', 377, 54, 0);
insert into tblBook values (book_seq.nextVal, '(뉴 52) 배트맨 4: 제로 이어 - 비밀의 도시', 'SoulHouse:소울하우스:아이씨티컴퍼니', '스콧 스나이더 ', 256, 46, 0);
insert into tblBook values (book_seq.nextVal, '스즈키 선생님 4', '아라크네', '다케토미 겐지 ', 470, 76, 0);
insert into tblBook values (book_seq.nextVal, '스즈키 선생님 2', '을파소:북이십일 을파소', '다케토미 겐지 ', 698, 61, 0);
insert into tblBook values (book_seq.nextVal, '스즈키 선생님 1', '고래가숨쉬는도서관', '다케토미 겐지 ', 434, 90, 0);
insert into tblBook values (book_seq.nextVal, '스즈키 선생님 3', '파란 :파란미디어', '다케토미 겐지 ', 845, 47, 0);
insert into tblBook values (book_seq.nextVal, '(뉴 52) 배트맨 3: 가족의 죽음', '피그마리온 :Easy&books', '스콧 스나이더 ', 919, 56, 0);
insert into tblBook values (book_seq.nextVal, '전염됩니다. 5', '갈무리', '요시다 센샤 ', 728, 74, 0);
insert into tblBook values (book_seq.nextVal, '전염됩니다. 4', '백문백답', '요시다 센샤 ', 360, 53, 0);
insert into tblBook values (book_seq.nextVal, '전염됩니다. 3', '라이스메이커', '요시다 센샤 ', 794, 31, 0);
insert into tblBook values (book_seq.nextVal, '전염됩니다. 2', 'Taste books:테이스트북스:문학동네', '요시다 센샤 ', 271, 05, 0);
insert into tblBook values (book_seq.nextVal, '토탈임팩트의 현대카드 디자인 이야기', 'Odos:오도스', '오영식', 432, 17, 0);
insert into tblBook values (book_seq.nextVal, '알코올 병동', '중앙books :중앙일보플러스', '아즈마 히데오 ', 482, 25, 0);
insert into tblBook values (book_seq.nextVal, '그래픽 디자인 사용 설명서', '썬더키즈 :썬더버드', '아드리안 쇼네시', 043, 36, 0);
insert into tblBook values (book_seq.nextVal, '토성 맨션 6', '사파리 :이퍼블릭', '이와오카 히사에 ', 198, 31, 0);
insert into tblBook values (book_seq.nextVal, '토성 맨션 7', '우주나무', '이와오카 히사에 ', 052, 12, 0);
insert into tblBook values (book_seq.nextVal, '토성 맨션 5', 'Bansok:반석출판사', '이와오카 히사에 ', 602, 39, 0);
insert into tblBook values (book_seq.nextVal, '도련님의 시대 5', '시그마북스', '다니구치 지로', 071, 20, 0);
insert into tblBook values (book_seq.nextVal, '도련님의 시대 4', '더스토리 :미르북컴퍼니', '다니구치 지로 ', 259, 22, 0);
insert into tblBook values (book_seq.nextVal, '오렌지 마말레이드 7', '까치', '석우 ', 336, 33, 0);
insert into tblBook values (book_seq.nextVal, '오렌지 마말레이드 6', '손안의책', '석우 ', 469, 36, 0);
insert into tblBook values (book_seq.nextVal, '오렌지 마말레이드 8', '모모북스', '석우 ', 897, 06, 0);
insert into tblBook values (book_seq.nextVal, '배트맨: 블랙 미러 2', '책읽는달', '스콧 스나이더 ', 825, 75, 0);
insert into tblBook values (book_seq.nextVal, '배트맨: 블랙 미러 1', '소우주', '스콧 스나이더 ', 584, 63, 0);
insert into tblBook values (book_seq.nextVal, '도련님의 시대 3', '세나북스', '다니구치 지로 ', 910, 70, 0);
insert into tblBook values (book_seq.nextVal, '도련님의 시대 2', '한울림어린이', '다니구치 지로 ', 336, 53, 0);
insert into tblBook values (book_seq.nextVal, '떠나기 전 마지막 입맞춤', '고릴라박스', '대니 그레고리   ', 933, 44, 0);
insert into tblBook values (book_seq.nextVal, '브레이크다운스', '교양인', '아트 슈피겔만 ', 724, 65, 0);
insert into tblBook values (book_seq.nextVal, '배트맨 앤솔로지', '올리브나무', '어반 코믹스 ', 072, 71, 0);
insert into tblBook values (book_seq.nextVal, '기계 장치의 사랑 2', '봄볕', '고다 요시이에 ', 378, 92, 0);
insert into tblBook values (book_seq.nextVal, '기계 장치의 사랑 1', '한빛라이프', '고다 요시이에 ', 664, 85, 0);
insert into tblBook values (book_seq.nextVal, '신 이야기', '젤리판다', '고다 요시이에 ', 808, 32, 0);
insert into tblBook values (book_seq.nextVal, '오렌지 마말레이드 4', 'BM성안당 :성안당', '석우 ', 738, 83, 0);
insert into tblBook values (book_seq.nextVal, '오렌지 마말레이드 5', '허밍버드 :백도씨', '석우 ', 137, 64, 0);
insert into tblBook values (book_seq.nextVal, '(뉴 52) 배트맨 2: 올빼미 도시', '티나', '스콧 스나이더 ', 830, 04, 0);
insert into tblBook values (book_seq.nextVal, '(뉴 52) 배트맨 1: 올빼미 법정', '통나무', '스콧 스나이더 ', 064, 84, 0);
insert into tblBook values (book_seq.nextVal, '배트맨: 가스등 아래의 고담', '타보름교육', '브라이언 어거스틴 ', 298, 43, 0);
insert into tblBook values (book_seq.nextVal, '트윈 스피카 7', '포레스트북스', '야기누마 고 ', 256, 24, 0);
insert into tblBook values (book_seq.nextVal, '트윈 스피카 8', '하루놀:스푼북', '야기누마 고 ', 978, 68, 0);
insert into tblBook values (book_seq.nextVal, '아직 최선을 다하지 않았을 뿐 4', '시공사', '아오노 &#49804;주 ', 581, 31, 0);
insert into tblBook values (book_seq.nextVal, '아직 최선을 다하지 않았을 뿐 5', '매일경제신문사:매경출판', '아오노 &#49804;주 ', 964, 27, 0);
insert into tblBook values (book_seq.nextVal, '루드비코의 만화∙영화', '파람북', '루드비코 ', 660, 52, 0);
insert into tblBook values (book_seq.nextVal, '아직 최선을 다하지 않았을 뿐 3', '한스미디어 :한즈미디어', '아오노 &#49804;주 ', 728, 87, 0);
insert into tblBook values (book_seq.nextVal, '아직 최선을 다하지 않았을 뿐 2', '파람북', '아오노 &#49804;주 ', 803, 49, 0);
insert into tblBook values (book_seq.nextVal, '두근두근 캠핑 로드 1', '폴라북스:현대문학', '하야세 준 ', 429, 79, 0);
insert into tblBook values (book_seq.nextVal, '두근두근 캠핑 로드 2', '시공주니어 :시공사', '하야세 준 ', 357, 43, 0);
insert into tblBook values (book_seq.nextVal, '두근두근 캠핑 로드 3', '반석출판사', '하야세 준 ', 665, 01, 0);
insert into tblBook values (book_seq.nextVal, '두근두근 캠핑 로드 4', '안전가옥', '하야세 준 ', 449, 21, 0);
insert into tblBook values (book_seq.nextVal, '두근두근 캠핑 로드 5', '티나', '하야세 준 ', 900, 54, 0);
insert into tblBook values (book_seq.nextVal, '두근두근 캠핑 로드 6', '인플루엔셜', '하야세 준 ', 333, 20, 0);
insert into tblBook values (book_seq.nextVal, '백성귀족 3', '아트인북', '아라카와 히로무 ', 285, 61, 0);
insert into tblBook values (book_seq.nextVal, '그래픽디자인 다이어리', '스튜디오다산 :다산어린이', '뤼시엔 로버츠', 249, 17, 0);
insert into tblBook values (book_seq.nextVal, '포의 일족 3', '로드북', '하기오 모토 ', 700, 17, 0);
insert into tblBook values (book_seq.nextVal, '포의 일족 2', '렛츠book:렛츠북', '하기오 모토 ', 735, 68, 0);
insert into tblBook values (book_seq.nextVal, '다 빈치와 최후의 만찬', '휴먼에듀 :휴먼어린이', '로스 킹 ', 067, 70, 0);
insert into tblBook values (book_seq.nextVal, '트윈 스피카 6', '더스토리 :미르북컴퍼니', '야기누마 고 ', 793, 88, 0);
insert into tblBook values (book_seq.nextVal, '트윈 스피카 5', '시그마북스', '야기누마 고 ', 583, 80, 0);
insert into tblBook values (book_seq.nextVal, '선생님의 가방 2', '국민서관', '다니구치 지로 ', 539, 53, 0);
insert into tblBook values (book_seq.nextVal, '선생님의 가방 1', 'Izi publishing:이지퍼블리싱', '다니구치 지로 ', 333, 69, 0);
insert into tblBook values (book_seq.nextVal, '겨울 동물원', '돋을새김', '다니구치 지로 ', 004, 02, 0);
insert into tblBook values (book_seq.nextVal, '트윈 스피카 4', '현암주니어 :현암사', '야기누마 고', 696, 20, 0);
insert into tblBook values (book_seq.nextVal, '모험 에레키테 섬 1', '알키 :시공사', '츠루타 겐지 ', 017, 84, 0);
insert into tblBook values (book_seq.nextVal, '그 남자의 모터사이클', 'Humanist :휴머니스트 출판그룹', '신동헌', 678, 01, 0);
insert into tblBook values (book_seq.nextVal, '사물 판독기', '책속물고기', '반이정', 468, 10, 0);
insert into tblBook values (book_seq.nextVal, '트윈 스피카 1', '춘명', '야기누마 고 ', 680, 36, 0);
insert into tblBook values (book_seq.nextVal, '트윈 스피카 2', '서사원', '야기누마 고 ', 429, 29, 0);
insert into tblBook values (book_seq.nextVal, '트윈 스피카 3', '매일경제신문사 :매경출판', '야기누마 고 ', 132, 42, 0);
insert into tblBook values (book_seq.nextVal, '한 살이라도 어릴 때', '시공사', '김진', 020, 35, 0);
insert into tblBook values (book_seq.nextVal, '사랑의 그림', '초록아이', '최정은', 807, 93, 0);
insert into tblBook values (book_seq.nextVal, '설국열차', '웅진지식하우스:웅진씽크빅', '자크 로브', 965, 57, 0);
insert into tblBook values (book_seq.nextVal, '포어사이트 크리에이터 foresight creator', '비채 :김영사', '이돈태', 405, 64, 0);
insert into tblBook values (book_seq.nextVal, 'AKIRA 1', '젤리판다', '오토모 가쓰히로 ', 059, 76, 0);
insert into tblBook values (book_seq.nextVal, 'AKIRA 2', '북드라망', '오토모 가쓰히로 ', 440, 79, 0);
insert into tblBook values (book_seq.nextVal, 'AKIRA 3', '한길사', '오토모 가쓰히로 ', 860, 80, 0);
insert into tblBook values (book_seq.nextVal, 'AKIRA 4', '두사람', '오토모 가쓰히로 ', 488, 49, 0);
insert into tblBook values (book_seq.nextVal, 'AKIRA 5', '유아이북스', '오토모 가쓰히로 ', 598, 35, 0);
insert into tblBook values (book_seq.nextVal, 'AKIRA 6', '현암주니어 :현암사', '오토모 가쓰히로 ', 368, 70, 0);
insert into tblBook values (book_seq.nextVal, 'AKIRA 세트 ', '한국수필가협회 :코드미디어', '오토모 가쓰히로 ', 964, 09, 0);
insert into tblBook values (book_seq.nextVal, '오렌지 마말레이드 3', 'Terra :테라', '석우 ', 790, 81, 0);
insert into tblBook values (book_seq.nextVal, '오렌지 마말레이드 2', '키스톤:에이스컨프로', '석우 ', 590, 08, 0);
insert into tblBook values (book_seq.nextVal, '오렌지 마말레이드1', 'GREENCOOK :그린쿡', '석우 ', 937, 79, 0);
insert into tblBook values (book_seq.nextVal, '인터뷰', '라이카미', '루드비코 ', 484, 50, 0);
insert into tblBook values (book_seq.nextVal, '런던 수집', '썬더키즈 :썬더버드', '이은이', 717, 63, 0);
insert into tblBook values (book_seq.nextVal, '아이고 I GO 1', '창비E :창비교육', '김우준 ', 278, 75, 0);
insert into tblBook values (book_seq.nextVal, '발작2', '니들북 :대원씨아이', '다비드 베 ', 341, 19, 0);
insert into tblBook values (book_seq.nextVal, '발작1', '라의눈', '다비드 베 ', 116, 59, 0);
insert into tblBook values (book_seq.nextVal, '그린 스마일 3', '허밍버드 :백도씨', '권혁주 ', 679, 89, 0);
insert into tblBook values (book_seq.nextVal, '그린 스마일 2', '청어람아이:청어람미디어', '권혁주 ', 089, 28, 0);
insert into tblBook values (book_seq.nextVal, '포의 일족 1', '초록아이', '하기오 모토 ', 816, 19, 0);
insert into tblBook values (book_seq.nextVal, '표류교실3', '마주별', '우메즈 카즈오 ', 062, 37, 0);
insert into tblBook values (book_seq.nextVal, '표류교실2', '넥서스biz :넥서스', '우메즈 카즈오 ', 470, 96, 0);
insert into tblBook values (book_seq.nextVal, '표류교실1', '북캠퍼스', '우메즈 카즈오 ', 182, 53, 0);
insert into tblBook values (book_seq.nextVal, '전염됩니다 1', '정은문고', '요시다 센샤 ', 320, 91, 0);
insert into tblBook values (book_seq.nextVal, '미술사 방법론', '심플라이프', '마이클 해트 ', 853, 59, 0);
insert into tblBook values (book_seq.nextVal, '도련님의 시대 1', '오올', '다니구치 지로 ', 250, 37, 0);
insert into tblBook values (book_seq.nextVal, '자유부인 하', '다른', '데니코 ', 988, 85, 0);
insert into tblBook values (book_seq.nextVal, '자유부인 상', '책밥', '데니코 ', 554, 52, 0);
insert into tblBook values (book_seq.nextVal, '토성 맨션 4', '길벗', '이와오카 히사에 ', 318, 15, 0);
insert into tblBook values (book_seq.nextVal, '토성 맨션 3', '교양인', '이와오카 히사에 ', 115, 33, 0);
insert into tblBook values (book_seq.nextVal, '그 남자의 자동차', '문학사상', '신동헌', 634, 46, 0);
insert into tblBook values (book_seq.nextVal, '1900년 이후의 미술사[개정판]', '봄봄:봄봄출판사', '할 포스터', 019, 74, 0);
insert into tblBook values (book_seq.nextVal, '배트맨: 헌티드 나이트', '어바웃어북', '제프 로브 ', 946, 68, 0);
insert into tblBook values (book_seq.nextVal, '배트맨: 망토 두른 십자군에게 무슨 일이 생겼나?', '한울림어린이', '닐 게이먼 ', 098, 43, 0);
insert into tblBook values (book_seq.nextVal, '배트맨: 나이트폴2', '비타북스 :헬스조선', '더그 먼치 ', 053, 78, 0);
insert into tblBook values (book_seq.nextVal, '배트맨: 나이트폴1', '이터', '더그 먼치 ', 488, 89, 0);
insert into tblBook values (book_seq.nextVal, '배트맨: 나이트폴3', '로드북', '더그 먼치 ', 025, 71, 0);
insert into tblBook values (book_seq.nextVal, '아직 최선을 다하지 않았을 뿐 1', '봄나무', '아오노주 ', 175, 46, 0);
insert into tblBook values (book_seq.nextVal, '백성귀족2', '두사람', '아라카와 히로무 ', 276, 11, 0);
insert into tblBook values (book_seq.nextVal, '캣우먼: 로마에서의 일주일', '피플앤북스', '제프 로브 ', 162, 93, 0);
insert into tblBook values (book_seq.nextVal, '배트맨: 다크 빅토리 1 (Batman: Dark Victory 1)', '티나', '제프 로브 ', 332, 74, 0);
insert into tblBook values (book_seq.nextVal, '배트맨: 다크 빅토리 2 (Batman: Dark Victory 2)', '이미출판사', '제프 로브 ', 437, 03, 0);
insert into tblBook values (book_seq.nextVal, '배트맨: 웃는 남자', '아르띠잔', '에드 브루베이커 ', 714, 68, 0);
insert into tblBook values (book_seq.nextVal, '배트맨: 패밀리의 죽음', '만개의레시피 :이지에이치엘디', '짐 스탈린 ', 967, 62, 0);
insert into tblBook values (book_seq.nextVal, '배트맨: 조커(JOKER)', '이터', '브라이언 아자렐로 ', 084, 18, 0);
insert into tblBook values (book_seq.nextVal, '영혼을 잃지 않는 일러스트레이터 되기', '시대의창', '데럴 리스 ', 819, 48, 0);
insert into tblBook values (book_seq.nextVal, '커피 한 잔 더 4', '창비교육', '야마카와 나오토 ', 749, 99, 0);
insert into tblBook values (book_seq.nextVal, '커피 한 잔 더 5', '늘품플러스', '야마카와 나오토 ', 579, 22, 0);
insert into tblBook values (book_seq.nextVal, '배트맨: 아캄 어사일럼(ARKHAM ASYLUM)', '어니스트북스 :어니스트펫', '그랜트 모리슨 ', 212, 76, 0);
insert into tblBook values (book_seq.nextVal, '포겟미낫(FORGET ME NOT)', '산처럼', '츠루타 겐지 ', 538, 58, 0);
insert into tblBook values (book_seq.nextVal, '스피릿오브원더(SPIRIT OF WONDER)', '꾸리에:꾸리에북스', '츠루타 겐지 ', 353, 27, 0);
insert into tblBook values (book_seq.nextVal, '윌슨', '휴머니스트 :휴머니스트 출판그룹', '대니얼 클로즈 ', 369, 67, 0);
insert into tblBook values (book_seq.nextVal, '다케시의 낙서 입문', '즐거운상상', '기타노 다케시 ', 180, 70, 0);
insert into tblBook values (book_seq.nextVal, '완벽하지 않아', '스몰빅라이프 :스몰빅미디어', '에이드리언 토미네 ', 128, 28, 0);
insert into tblBook values (book_seq.nextVal, '가지 하', '북캠퍼스', '구로다 이오우 ', 371, 97, 0);
insert into tblBook values (book_seq.nextVal, '배트맨: 롱 할로윈 2', '베이직북스', '제프 로브 ', 698, 58, 0);
insert into tblBook values (book_seq.nextVal, '배트맨: 롱 할로윈 1', '청어람i아이:청어람미디어', '제프 로브 ', 404, 80, 0);
insert into tblBook values (book_seq.nextVal, '증거 2', '애플북스 :비전비엔피', '이승찬 ', 743, 38, 0);
insert into tblBook values (book_seq.nextVal, '증거 1', '북핀', '이승찬 ', 158, 03, 0);
insert into tblBook values (book_seq.nextVal, '걸작의 뒷모습', '이봄', '세라 손튼 ', 924, 60, 0);
insert into tblBook values (book_seq.nextVal, '의자의 재발견', '달아실', '김상규', 475, 52, 0);
insert into tblBook values (book_seq.nextVal, '꿈의 포로 아크파크 5 [2.333차원]', '서사원', '마르크앙투안 마티외 ', 918, 07, 0);
insert into tblBook values (book_seq.nextVal, '공간의 요정', '마더북스', '김한민 ', 279, 80, 0);
insert into tblBook values (book_seq.nextVal, '글리머 디자인이 반짝하는 순간', '걷는사람', '워렌 버거 ', 197, 13, 0);
insert into tblBook values (book_seq.nextVal, '해외에서 디자이너로 살아가기', '인물과사상사', '민혜원', 466, 04, 0);
insert into tblBook values (book_seq.nextVal, '꿈의 포로 아크파크 4 [시작의 끝]', '티나', '마르크앙투안 마티외 ', 498, 62, 0);
insert into tblBook values (book_seq.nextVal, '꿈의 포로 아크파크 3 [프로세스]', '중앙books :중앙일보플러스', '마르크앙투안 마티외 ', 759, 43, 0);
insert into tblBook values (book_seq.nextVal, '꿈의 포로 아크파크 2 [사....]', '아라크네', '마르크앙투안 마티외 ', 075, 36, 0);
insert into tblBook values (book_seq.nextVal, '꿈의 포로 아크파크 1 [기원]', '뜨인돌', '마르크앙투안 마티외 ', 154, 29, 0);
insert into tblBook values (book_seq.nextVal, '백성귀족 1', '토토북', '아라카와 히로무 ', 643, 84, 0);
insert into tblBook values (book_seq.nextVal, '가지 상', '이담 Books :한국학술정보', '구로다 이오우 ', 464, 75, 0);
insert into tblBook values (book_seq.nextVal, '실종일기', '미래의창', '아즈마 히데오 ', 412, 85, 0);
insert into tblBook values (book_seq.nextVal, '나는 예술가다', '인물과사상사', '권근영', 357, 08, 0);
insert into tblBook values (book_seq.nextVal, '스즈키 선생님 1', 'BM성안북스', '다케토미 겐지 ', 119, 55, 0);
insert into tblBook values (book_seq.nextVal, '그린 스마일 1', 'Andromedian :안드로메디언 :로크미디어', '권혁주 ', 230, 46, 0);
insert into tblBook values (book_seq.nextVal, '배트맨 킬링 조크', 'Editus:에디투스', '앨런 무어  ', 890, 77, 0);
insert into tblBook values (book_seq.nextVal, 'K[케이]', '이케이북', '도사키 시로 ', 670, 21, 0);
insert into tblBook values (book_seq.nextVal, '사가판 어류도감', '진선아트북:진선출판사', '모로호시 다이지로 ', 514, 46, 0);
insert into tblBook values (book_seq.nextVal, '사가판 조류도감', '다산어린이 :스튜디오다산', '모로호시 다이지로 ', 310, 89, 0);
insert into tblBook values (book_seq.nextVal, '커피 한 잔 더 3', '토토북', '야마카와 나오토 ', 168, 52, 0);
insert into tblBook values (book_seq.nextVal, '무서운 그림 3', '제제의숲', '나카노 교코 ', 063, 43, 0);
insert into tblBook values (book_seq.nextVal, '이상한 나라의 앨리스', '소와다리', '다비드 쇼벨 ', 318, 37, 0);
insert into tblBook values (book_seq.nextVal, '꿈꾸는 미술 공장, 베이징 일기', '아카넷', '한혜경', 281, 91, 0);
insert into tblBook values (book_seq.nextVal, '11인이 있다!', '그린비:그린비출판사', '하기오 모토 ', 248, 43, 0);
insert into tblBook values (book_seq.nextVal, '자학의 시 2', 'BnCworld:비앤씨월드', '고다 요시이에 ', 389, 33, 0);
insert into tblBook values (book_seq.nextVal, '자학의 시 1', '미디어창비', '고다 요시이에 ', 413, 56, 0);
insert into tblBook values (book_seq.nextVal, '배트맨: 다크 나이트 스트라이크 어게인', '어바웃어북', '프랭크 밀러 ', 109, 19, 0);
insert into tblBook values (book_seq.nextVal, '무서운 그림 2', '블루홀6:블루홀식스', '나카노 교코 ', 849, 54, 0);
insert into tblBook values (book_seq.nextVal, '사우나맨', '북스톤', '이명하 ', 886, 07, 0);
insert into tblBook values (book_seq.nextVal, '아돌프에게 고한다 5', 'Hu:ine :한국외국어대학교 지식출판콘텐츠원', '데즈카 오사무 ', 762, 22, 0);
insert into tblBook values (book_seq.nextVal, '아돌프에게 고한다 4', '라이카미', '데즈카 오사무 ', 955, 08, 0);
insert into tblBook values (book_seq.nextVal, '아돌프에게 고한다 3', '한겨례아이들 :한겨레출판', '데즈카 오사무 ', 060, 07, 0);
insert into tblBook values (book_seq.nextVal, '아돌프에게 고한다 2', 'Human & Books', '데즈카 오사무 ', 239, 38, 0);
insert into tblBook values (book_seq.nextVal, '아돌프에게 고한다 1', '오올', '데즈카 오사무 ', 831, 37, 0);
insert into tblBook values (book_seq.nextVal, '창작 면허 프로젝트', '21세기북스 :북이십일 21세기북스', '대니 그레고리   ', 999, 76, 0);
insert into tblBook values (book_seq.nextVal, '트랜스포머 : 로봇 내전 2', '가람어린이', '사이먼 퍼먼 ', 266, 25, 0);
insert into tblBook values (book_seq.nextVal, '우연한 걸작', '제철소', '마이클 키멜만 ', 479, 93, 0);
insert into tblBook values (book_seq.nextVal, '지미 코리건: 세상에서 가장 똑똑한 아이', '우주나무', '크리스 웨어 ', 306, 14, 0);
insert into tblBook values (book_seq.nextVal, '트랜스포머 : 로봇 내전 1', '미메시스', '사이먼 퍼먼 ', 054, 79, 0);
insert into tblBook values (book_seq.nextVal, '토성 맨션 2', '세종서적', '이와오카 히사에 ', 263, 99, 0);
insert into tblBook values (book_seq.nextVal, '트랜스포머: 무비 프리퀼', '제우미디어', '크리스 리얼', 963, 04, 0);
insert into tblBook values (book_seq.nextVal, '트랜스포머: 강철의 혼', '이지스퍼블리싱', '척 딕슨 ', 245, 30, 0);
insert into tblBook values (book_seq.nextVal, '트랜스포머: 더 무비', '그린비:그린비출판사', '로베르토 오시', 245, 32, 0);
insert into tblBook values (book_seq.nextVal, '리틀 포레스트 2', '아름다운사람들', '이가라시 다이스케 ', 988, 01, 0);
insert into tblBook values (book_seq.nextVal, '한글+한글디자인+디자이너', '한국수필가협회 :코드미디어', '이용제', 122, 78, 0);
insert into tblBook values (book_seq.nextVal, '배트맨: 이어 원', '을파소:북이십일 을파소', '프랭크 밀러', 709, 58, 0);
insert into tblBook values (book_seq.nextVal, '파레포리', '한겨례아이들 :한겨레출판', '후루야 우사마루 ', 713, 23, 0);
insert into tblBook values (book_seq.nextVal, '르네상스 미술이야기2', '강', '조승연 ', 590, 78, 0);
insert into tblBook values (book_seq.nextVal, '커피 한 잔 더 2', 'Taste books:테이스트북스:문학동네', '야마카와 나오토 ', 652, 13, 0);
insert into tblBook values (book_seq.nextVal, '리틀 포레스트 1', '고래뱃속', '이가라시 다이스케 ', 439, 35, 0);
insert into tblBook values (book_seq.nextVal, '니지가하라 홀로그래프', '더스토리 :미르북컴퍼니', '아사노 이니오 ', 920, 12, 0);
insert into tblBook values (book_seq.nextVal, '무서운 그림', '홍성사', '나카노 교코 ', 326, 66, 0);
insert into tblBook values (book_seq.nextVal, '배트맨: 다크 나이트 리턴즈2', '푸른숲주니어:푸른숲', '프랭크 밀러 ', 323, 06, 0);
insert into tblBook values (book_seq.nextVal, '배트맨: 다크 나이트 리턴즈1', '와이즈맵', '프랭크 밀러 ', 772, 25, 0);
insert into tblBook values (book_seq.nextVal, '토성 맨션 1', '청미디어', '이와오카 히사에 ', 978, 36, 0);
insert into tblBook values (book_seq.nextVal, '배트맨 허쉬 1', '벤트리', '제프 로브 ', 987, 54, 0);
insert into tblBook values (book_seq.nextVal, '배트맨 허쉬 2', '더퀘스트 :길벗', '제프 로브 ', 398, 99, 0);
insert into tblBook values (book_seq.nextVal, '배트맨: 악마의 십자가', '흐름출판', '조지 프랫 ', 301, 78, 0);
insert into tblBook values (book_seq.nextVal, '혜성을 닮은 방 3', '동인랑', '김한민 ', 694, 33, 0);
insert into tblBook values (book_seq.nextVal, '커피 한 잔 더 1', 'BM성안당:성안당', '야마카와 나오토 ', 905, 40, 0);
insert into tblBook values (book_seq.nextVal, '혜성을 닮은 방 2', '시그마북스', '김한민 ', 070, 92, 0);
insert into tblBook values (book_seq.nextVal, '샤갈의 다프니스와 클로에', '북카라반', '롱고스 ', 422, 59, 0);
insert into tblBook values (book_seq.nextVal, '샤갈의 아라비안 나이트', '아울북 :북이십일 아울북', '리처드 F. 버턴 ', 633, 05, 0);
insert into tblBook values (book_seq.nextVal, '혜성을 닮은 방 1', '발행사', '김한민 ', 849, 16, 0);
insert into tblBook values (book_seq.nextVal, '미술, 세상에 홀리다', '교유당', '줄리언 스팰딩 ', 407, 21, 0);
insert into tblBook values (book_seq.nextVal, '르네상스 미술이야기 1', '다산에듀 :다산북스', '조승연 ', 902, 97, 0);
insert into tblBook values (book_seq.nextVal, '광대의 노래 [2008 달력]', '고릴라박스', '백성민 ', 297, 97, 0);
insert into tblBook values (book_seq.nextVal, '광대의 노래', '현대지성', '백성민 ', 439, 32, 0);
insert into tblBook values (book_seq.nextVal, '스위스 그래픽 디자인', '문예출판사', '리처드 홀리스 ', 837, 97, 0);
insert into tblBook values (book_seq.nextVal, '좋은 디자인을 만드는 33가지 서체 이야기', '청년의사', '김현미', 320, 08, 0);
insert into tblBook values (book_seq.nextVal, '창고 라이브', '별숲', '지피 ', 741, 97, 0);
insert into tblBook values (book_seq.nextVal, '반고흐, 사랑과 광기의 나날', '북로드:더난콘텐츠그룹', '데릭 펠 ', 943, 71, 0);
insert into tblBook values (book_seq.nextVal, '고스트 월드', '팜파스', '대니얼 클로즈 ', 155, 89, 0);
insert into tblBook values (book_seq.nextVal, '아이스 헤이번', '웅진지식하우스:웅진씽크빅', '대니얼 클로즈 ', 582, 81, 0);
insert into tblBook values (book_seq.nextVal, '푸른 알약(증보판)', '꿈초:키즈엠', '프레데릭 페테르스  ', 354, 87, 0);
insert into tblBook values (book_seq.nextVal, '다이앤 아버스', '알키 :시공사', '퍼트리샤 보스워스 ', 695, 03, 0);
insert into tblBook values (book_seq.nextVal, '300', '내친구의서재', '프랭크 밀러 ', 184, 17, 0);
insert into tblBook values (book_seq.nextVal, '영혼을 잃지 않는 디자이너 되기', '키스톤:에이스컨프로', '아드리안 쇼네시 ', 654, 72, 0);
insert into tblBook values (book_seq.nextVal, '씬시티 세트', '필로소픽', '프랭크 밀러 ', 478, 57, 0);
insert into tblBook values (book_seq.nextVal, '씬시티 6', '한겨례아이들 :한겨레출판', '프랭크 밀러 ', 106, 33, 0);
insert into tblBook values (book_seq.nextVal, '씬시티 7', '풀빛', '프랭크 밀러 ', 810, 13, 0);
insert into tblBook values (book_seq.nextVal, '씬시티 5', '문학동네', '프랭크 밀러 ', 249, 09, 0);
insert into tblBook values (book_seq.nextVal, '9가지 키워드로 읽는 디자인', '베틀북', '오창섭 ', 138, 42, 0);
insert into tblBook values (book_seq.nextVal, '씬시티 4', '북멘토', '프랭크 밀러 ', 805, 88, 0);
insert into tblBook values (book_seq.nextVal, '대한인디만세', '도림북스', '박준흠 ', 236, 67, 0);
insert into tblBook values (book_seq.nextVal, '씬시티 3', '청미디어', '프랭크 밀러 ', 106, 52, 0);
insert into tblBook values (book_seq.nextVal, '씬시티 2', '아모르문디', '프랭크 밀러 ', 004, 70, 0);
insert into tblBook values (book_seq.nextVal, '씬시티 1', '학연문화사', '프랭크 밀러 ', 431, 30, 0);
insert into tblBook values (book_seq.nextVal, '클래식광,그림을 읽다', 'ilda:일다', '이장현', 932, 33, 0);
insert into tblBook values (book_seq.nextVal, '기억을 잃어버린 도시', '마음산책', '김진송 ', 746, 91, 0);
insert into tblBook values (book_seq.nextVal, '모든 날이 소중하다', '따비', '대니 그레고리   ', 622, 24, 0);
insert into tblBook values (book_seq.nextVal, '우리에게도 따뜻한 날이 올까', '잇츠북어린이', '신현림 ', 317, 85, 0);
insert into tblBook values (book_seq.nextVal, '로고와 이쑤시개', '다산북스', '존 헤스켓 ', 633, 84, 0);
